ets-berkeley-edu/suitec

deploy/collabosphere.conf, deploy/deploy.sh, node_modules/col-core/lib/api.js, node_modules/col-core/lib/logger.js
I added an upstart script that "daemonizes" collabosphere. It will keep respawning the node process when it crashes (up to 10 times per minute, it stops after that).
I also added an uncaughtException handler that will print the failure to the logs before exitting.
=> COL-83 - Upstart script

node_modules/col-core/lib/db.js, node_modules/col-users/tests/test-users.js, node_modules/col-users/tests/util.js
For example, somehow I ended up as: `Instructor,urn:lti:instrole:ims/lis/Administrator` on my local instance
=> Canvas can return multiple roles over LTI

node_modules/col-assets/tests/test-assets.js, node_modules/col-rest/lib/rest/whiteboards.js, node_modules/col-whiteboards/lib/api.js, node_modules/col-whiteboards/lib/rest.js, node_modules/col-whiteboards/tests/test-whiteboards.js, node_modules/col-whiteboards/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-387 (back end component of https://jira.ets.berkeley.edu/jira/browse/COL-380)
Note the new analytics event 'Search whiteboards', which might require additional integration on the Mixpanel side.
=> COL-387 Allow whiteboard search and filter - back end

scripts/col-repl.js
https://jira.ets.berkeley.edu/jira/browse/COL-413
I've found this handy enough during local development that I decided to submit it. Rails devs will recognize it as a sketchy gesture toward a Rails console-like environment.
Example usage:
```
% node scripts/col-repl
Loading Collabosphere environment...
[2016-07-21T19:29:48.883Z]  INFO: col-core/email/43411 on MacBook-Pro-2.local: No image manifest found in the document root. Using development assets (documentRoot=/var/www/html)
[2016-07-21T19:29:48.900Z]  INFO: col-activities/43411 on MacBook-Pro-2.local: Scheduling daily notifications for 2016-07-22T08:00:00-07:00 (in 70211998 ms)
Collabosphere environment loaded. Enjoy!
col-repl> CourseAPI.getCourses(function(err, courses) { log.info(courses[0].dataValues); });
undefined …
```
=> COL-413 Script for Node REPL with preloaded Collabosphere environment

config/default.json, node_modules/col-activities/lib/notifications/weekly.js
https://jira.ets.berkeley.edu/jira/browse/COL-401
Notes:
- This code has been exercised locally in the console, but there are no tests yet. Integration tests will follow once data is hooked up to the email template.
- Two not-yet-implemented activity types are assumed: `whiteboard_add_asset` and `whiteboard_chat`.
- Keyword counts for the week are to be added in a later task.
- User leaderboard ranks, present and past, are to be added in a later task.
- For now, weekly email scheduling is arbitrarily configured to Friday at noon. This configuration is used in setting the date range for the activities query, but is not yet added to the scheduling code in `col-activities/lib/notifications/api.js`.
=> COL-401 Collect weekly activity summaries for use in email template

node_modules/col-activities/lib/notifications/weekly.js, node_modules/col-users/lib/api.js, node_modules/col-users/lib/constants.js, node_modules/col-users/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-400
Since we need both points and email addresses for users, the function signature of UsersAPI.getLeaderboard is expanded to include an `options` object, following the pattern of UsersAPI.getAllUsers. These changes are opaque to our current integration test suite, but will need to be covered in integration tests for the weekly email.
The various permutations for rank calculation will also need test coverage.
=> COL-400 Calculate current user ranks for weekly email

config/travis.js, node_modules/col-activities/lib/notifications/weekly.js, node_modules/col-activities/lib/rest.js, node_modules/col-activities/tests/test-daily.js, node_modules/col-activities/tests/test-weekly.js, node_modules/col-activities/tests/util.js, node_modules/col-rest/lib/rest/activities.js
https://jira.ets.berkeley.edu/jira/browse/COL-425
An admin-only magic URL is exposed to trigger the weekly email. This URL is also used for the first integration tests; more to come. 
Note that many utility functions are moved from `node_modules/col-activities/tests/test-daily.js` into `node_modules/col-activities/tests/util.js` so that both daily and the weekly email tests can use them.
=> COL-425 Allow course admins to manually trigger weekly email from the browser

node_modules/col-core/lib/db.js, node_modules/col-course/lib/api.js, node_modules/col-lti/lib/api.js, scripts/20160824-col434/add_course_engagementindex_url.sql
https://jira.ets.berkeley.edu/jira/browse/COL-434
The weekly email requires a stored URL for the engagement index, as we already do for the other two SuiteC tools.
=> COL-434 Add per-course engagementindex_url property

node_modules/col-activities/lib/notifications/weekly.js
https://jira.ets.berkeley.edu/jira/browse/COL-424
The weekly email front end is already set up to show a placeholder icon for users lacking properties.
Test coverage for this feature will come with the rest of the integration suite.
=> COL-424 Weekly email: anonymize users not opted into engagement index

node_modules/col-activities/lib/default.js, node_modules/col-activities/tests/test-csv.js, node_modules/col-activities/tests/test-points.js, node_modules/col-activities/tests/util.js, node_modules/col-assets/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-395
Rounding out work done by @johncrossman. Following the logic for other activity types, no distinct activity is logged for a user viewing their own asset.
The integration tests, being integration tests, are sensitive to the appearance of this new activity type and needed some massaging. The `w=1` option is recommended for review.
=> COL-395 Add view_asset activity type

email-templates/weekly/html.ejs, email-templates/weekly/style.scss, node_modules/col-activities/data/radarChart.js, node_modules/col-activities/lib/notifications/weekly.js, node_modules/col-core/lib/constants.js
https://jira.ets.berkeley.edu/jira/browse/COL-397
We generate one chart per user per week, and for the moment are simply storing them as PNG files on disk in a directory accessible to Apache. Generated files are between 17-20 kB; a script to delete older files after a certain point might be an advisable follow-up.
=> COL-397 Add radar chart to weekly email

node_modules/col-core/lib/api.js, node_modules/col-core/lib/rest.js, node_modules/col-core/tests/test-status.js, node_modules/col-rest/lib/rest/core.js
https://jira.ets.berkeley.edu/jira/browse/COL-472
For Nagios reasons, Ops prefers that the /api/status feed not be subject to regular change.
=> COL-472 Move version number reporting to its own feed

config/default.json, node_modules/col-activities/lib/api.js, node_modules/col-activities/lib/notifications/weekly.js, node_modules/col-activities/tests/test-weekly.js, node_modules/col-activities/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-444
Per user request, weekly emails are set to Monday morning by default.
Includes a second commit to skip the weekly email for courses where the asset library or engagement index is not enabled.
=> COL-444 Schedule weekly email on app startup

email-templates/_shared/style.css, email-templates/weekly/style.scss
https://jira.ets.berkeley.edu/jira/browse/COL-476
These email templates have no access to any sass-type extension that would let us define a constant.
=> COL-476 Weekly email: use darker light gray

node_modules/col-assets/lib/api.js, node_modules/col-whiteboards/lib/api.js, public/app/assetlibrary/iconbar/assetLibraryIconBarController.js, public/app/assetlibrary/item/assetLibraryItemController.js, public/app/whiteboards/board/whiteboardsBoardDirective.js, public/assets/js/bookmarklet.js
https://jira.ets.berkeley.edu/jira/browse/COL-491
col-assets and col-whiteboards need better Nouveau Lodash.
Also - while I'm unaware of this causing actual bugs  - Lodash syntax updates in front-end code are reverted for the moment. The front end is using a separate, earlier version of Lodash (as defined in bower.json) and updating that should be a distinct task.
=> COL-491 Fix syntax updates in whiteboard API

deploy/deploy.sh, deploy/install-locally.sh
https://jira.ets.berkeley.edu/jira/browse/COL-490
The install-locally script should be useful for reseting your local third-party dependencies. Note: added verbosity w.r.t the significant DOCUMENT_ROOT var.
=> COL-490, install-locally.sh script; remove contextify from deploy script

apache/collabosphere.template, gulpfile.js, node_modules/col-core/lib/db.js, node_modules/col-lti/lib/api.js, node_modules/col-lti/lib/rest.js, public/app/assetlibrary/item/assetLibraryItemController.js, public/app/assetlibrary/list/assetLibraryListController.js, public/app/shared/utilService.js, public/app/whiteboards/list/whiteboardsListController.js, public/assets/js/canvas-customization.js, scripts/20161003-col499/add_canvas_supports_custom_messaging.sql
https://jira.ets.berkeley.edu/jira/browse/COL-499
Core SuiteC features, including tool resizing, scrolling and deeplinks, are dependent on custom cross-window messages, support for which must be added to the hosting Canvas instance. Where possible, add fallbacks when this support is not present. In all cases, make the dependency more explicit. 
- The 'canvas' table is altered to specify whether a Canvas instance supports custom messaging.
- This information is made available to the front end through a cookie on LTI launch. If custom messages are not supported, the front end should not send them.
- Fallbacks for scrolling and tool resizing are implemented.
- A fallback for deep links is out of scope for this PR. The lack of functionality is documented.
- Relevant Canvas customization code …
=> COL-499 Add fallbacks for Canvas instances without custom cross-window messaging

node_modules/col-canvas/lib/poller.js, node_modules/col-canvas/tests/test-poller.js, scripts/20161109-col517/remove_old_discussion_activities.js
https://jira.ets.berkeley.edu/jira/browse/COL-473
Once this new logic is in place, the poller should gamely sweep through and pick up older discussion activities in the new format. Discussion activities in the old format will appear as duplicates. The migration script to remove those duplicates should be run post-release, once we've confirmed that the new poller logic is working as expected.
=> COL-473 Award EI points for multiple postings to a topic

scripts/20160910-col398/add_category_visible.sql
https://jira.ets.berkeley.edu/jira/browse/COL-458
Migrations to adjust database structure are already in place. This addition ensures that categories derived from assignments start out invisible.
=> COL-458 Make Canvas assignment categories invisible

public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-416
The `Download` button has been moved up, between `Edit` and `Delete`. The min number of buttons a user can see is one and the max is three - this is why bootstrap `col-xs` configs changed and `canManageAsset()` was move to control only the `Edit` button.
=> COL-416, allow PDFs and other assets to be downloaded

node_modules/col-canvas/lib/poller.js
A fix for the reopened https://jira.ets.berkeley.edu/jira/browse/COL-473.
=> COL-473 Track discussion replies by reply ID, not parent entry ID

node_modules/col-canvas/lib/poller.js, node_modules/col-canvas/tests/model.js, node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-537
The criterion for "who are you replying to?" should not be "who originally started the thread?"; it should be "who are you replying to?".
=> COL-537 Fix activity-tracking logic for threaded discussions

docs/deployment.md
https://jira.ets.berkeley.edu/jira/browse/COL-538
I noticed this extraneous instruction when reviewing release-instructions doc.
=> COL-538, we need not 'get latest code' when deploying to network

node_modules/col-canvas/lib/poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-541
Since orphaned replies will call this every time the poller runs, a big grumpy error log is too noisy.
=> COL-541 Lower log level on discussion replies with missing parents

node_modules/col-canvas/lib/poller.js, node_modules/col-canvas/tests/test-poller.js, node_modules/col-core/lib/constants.js, node_modules/col-tests/lib/util.js, node_modules/col-users/tests/test-users.js, node_modules/col-whiteboards/tests/test-whiteboards.js, scripts/20161121-col516/update_canvas_course_role_values.sql
https://jira.ets.berkeley.edu/jira/browse/COL-516
Roles are recorded using full URN as seen in [LTI implementation-guide](https://www.imsglobal.org/specs/ltiv1p0/implementation-guide). Using namespaces avoids confusion with, for example, the `Instructor` role which is applicable in two contexts: institutional and course-level.
SQL script to migrate user data is included.
=> COL-516, roles are course-specific; full URNs in LTI spec describe context

scripts/20161121-col497/default_canvas_timestamp_values.sql
https://jira.ets.berkeley.edu/jira/browse/COL-497
See http://www.revsys.com/blog/2006/aug/04/automatically-updating-a-timestamp-column-in-postgresql/
=> COL-497 Default created_at and updated_at values in Canvas table

node_modules/col-core/lib/constants.js
https://jira.ets.berkeley.edu/jira/browse/COL-516
We are rolling forward on PR #220 by supporting both deprecated and full URN role names.
=> COL-516, Teacher role matches with LTI instructor full URN and short-name; ContentDeveloper, too

deploy/deploy.sh
If there are no post-deploy tasks then Ops can run:
```
./deploy/deploy.sh -t 1.63 && ./deploy/start.sh
```
we must `exit 1` when `echo_usage` such that *start.sh* won't run in example above.
=> NOJIRA, remove start.sh from deploy.sh; post-deploy tasks might require downtime

node_modules/col-activities/tests/util.js, node_modules/col-assets/lib/migrate.js, node_modules/col-assets/lib/rest.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/util.js, node_modules/col-course/lib/api.js, node_modules/col-course/lib/rest.js, node_modules/col-course/tests/test-course.js, node_modules/col-course/tests/util.js, node_modules/col-rest/lib/rest/assets.js, node_modules/col-rest/lib/rest/course.js, public/app/app.states.js, public/app/assetlibrary/assetLibraryFactory.js, public/app/assetlibrary/list/list.html, public/app/assetlibrary/manageassets/assetLibraryManageAssetsController.js, public/app/assetlibrary/manageassets/manageassets.css, public/app/assetlibrary/manageassets/manageassets.html, public/app/shared/courseFactory.js, public/index.html, scripts/migrate_assets.js
https://jira.ets.berkeley.edu/jira/browse/COL-528
This large PR is split into three commits for more manageable review.
The first commit moves asset migration logic into a module which is accessible both from the existing script and from a REST endpoint. Validation, sanity checks and tests are added.
The second commit creates a REST endpoint to list all courses associated with a user's Canvas account. We need this in order to display asset migration options to the user. The course listing includes filters relevant to this use case: 1) show only courses where I am an admin; 2) show only courses that are using the Asset Library; 3) don't show the current course.
The third commit includes front-end changes. The "Manage Categories" page becomes a "Manage Assets" page. The asset migration …
=> COL-528 Make asset migration accessible to admins from the browser

node_modules/col-users/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-587
This fixes a frequent test failure. The test expects case-insensitive ordering; code was performing a case-sensitive ordering; whether or not they matched depended entirely on the random strings.
=> COL-587 List users with case-insensitive ordering

node_modules/col-activities/lib/api.js, node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-524
Without this constraint, null `last_activity` values preempt not-null values in the `findOne` query below.
=> COL-524 Exclude users without activity when calculating last activity for course

public/app/assetlibrary/list/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-568
Screen reader wants its whitespace. Also use `div` for block-level elements, instead of inline elements with `display: block` styling.
=> COL-568 Properly format asset titles for screen reader

public/app/engagementindex/leaderboard/leaderboardController.js, public/app/engagementindex/leaderboard/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-567
Also fixes a couple of bugs: 
- normal/reverse sort order was toggled even when switching between columns;
- the `reverse` variable meant the opposite of what it said.
=> COL-567 Voice Engagement Index sorting in screenreader

node_modules/col-course/lib/api.js, node_modules/col-course/tests/test-course.js
https://jira.ets.berkeley.edu/jira/browse/COL-646
Updating this timestamp ensures that poller reactivation will stick even if there's been no other activity logged in the meantime.
=> COL-646 Update user's last_activity on poller reactivation

buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-658
This `buildspec.yml` was used to deploy via CodePipeline:
=> [eb-master] COL-658, buildspec.yml for AWS CodeBuild

config/default.json, node_modules/col-core/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-655
Some SuiteC courses are now large enough that polling a single course takes longer than our five-minute timeout, which is raising false alarms. Bump the timeout to ten minutes and make it configurable.
=> COL-655 Introduce configurable timeouts for background jobs

node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-655
Production logs suggest that successful runs of whiteboardToPng.js generally complete in less than 5 seconds, occasionally between 5 and 10.
=> COL-655 Handle timeouts on whiteboard PNG generation

node_modules/col-assets/lib/api.js, node_modules/col-canvas/lib/api.js, node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-642
Whiteboard image uploads to Canvas should have consistent filenames so that the new will overwrite the old.
Filenames on the local filesystem keep their timestamps so that multiple iterations of the write-upload-delete process won't trip over each other.
=> COL-642 Do not timestamp whiteboard exports in Canvas filesystem

public/app/assetlibrary/item/item.html, public/app/assetlibrary/list/list.html, public/app/assetlibrary/manageassets/manageassets.html, public/app/engagementindex/leaderboard/leaderboard.html, public/app/engagementindex/points/points.html, public/app/shared/copyright.html, public/app/whiteboards/list/list.html, public/assets/css/main.css
https://jira.ets.berkeley.edu/jira/browse/COL-462
As discussed at the ticket, the infinite scroll in the asset and whiteboard lists means that the notice will get pushed down fairly quickly on those pages, but no one can deny it's there.
=> COL-462 Add UC copyright language

public/app/assetlibrary/item/item.html, public/app/assetlibrary/list/list.html, public/app/assetlibrary/manageassets/manageassets.html
https://jira.ets.berkeley.edu/jira/browse/COL-462
Follow-up to #296: some fanciness with wrapper divs and `ui-view` was causing the notice to appear twice.
=> COL-462 Place copyright notice within wrapper divs

node_modules/col-whiteboards/lib/api.js, public/app/whiteboards/exportasassetmodal/exportasasset.html, public/app/whiteboards/exportasassetmodal/whiteboardsExportAsAssetController.js
https://jira.ets.berkeley.edu/jira/browse/COL-680
If whiteboard export is blocked by element preview status, show a more helpful message on both PNG downloads and Asset Library exports.
=> COL-680 Improve messaging on whiteboard export failure

config/default.json, node_modules/col-activities/lib/rest.js, node_modules/col-core/lib/email.js, node_modules/col-core/lib/logger.js, node_modules/col-whiteboards/lib/api.js, node_modules/col-whiteboards/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-508
Neither of the levels in our logging stack, https://www.npmjs.com/package/bunyan or
https://www.npmjs.com/package/bunyan-prettystream (whose developer says, "This library is only really meant for development and should not be used on production environments"), allow for timestamp formatting as such. However, we can elbow our way in by wrapping the individual logger functions.
=> COL-508 Configurable timezone setting for app and logs

node_modules/col-canvas/lib/api.js, node_modules/col-canvas/lib/poller.js, node_modules/col-canvas/tests/test-poller.js, node_modules/col-canvas/tests/util.js, public/app/assetlibrary/manageassets/manageassets.html, scripts/20170314-col675/add_sync_files.sql
https://jira.ets.berkeley.edu/jira/browse/COL-675
The sheer number of to-be-deleted submission files in production means that a separate cleanup script isn't practical. Instead the poller will have to clean up its act as it goes along, requiring changes to the finicky process of submission syncing and tracking.
=> COL-675 Do not sync assignment submissions unless sync explicitly enabled

apache/suitec.template, node_modules/col-lti/lib/constants.js, scripts/20170315-col707/add_dashboard_url_to_courses.sql
https://jira.ets.berkeley.edu/jira/browse/COL-706
https://jira.ets.berkeley.edu/jira/browse/COL-707
https://jira.ets.berkeley.edu/jira/browse/COL-708
Introduction of the new LTI tool begins with proposed naming: Dashboard. Of course, the content of the "Impact Studio" landing page is up to UX / Service Lead. Nonetheless, I'd prefer to keep under-the-hood naming descriptive, generalized and NOT based on transient grant initiatives.
Before I proceed with such naming I use this PR to get approval from da team.
=> COL-706, Impact Studio LTI tool gets general purpose name: Dashboard

.gitignore
An overdue fix. PDG devs will need to regenerate Apache config locally to pick up new LTI tool (dashboard). We don't want the generated `suitec.conf` to end up in Git repo.
cc: @paulkerschen @sandeepmjay
=> NOJIRA, update .gitignore with: apache/suitec.conf

node_modules/col-users/lib/rest.js, public/app/app.bootstrap.js, public/app/app.states.js, public/app/dashboard/myactivity.html, public/app/dashboard/splashController.js, public/app/shared/userFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-737
* change to `app.bootstrap.js` will parse out GET params from window.location
* new `/profile/:id` path takes advantage of `id_parameter` made available by change above
* I have put off the renaming of files, paths.  We'll refactor once official name is in.
=> COL-737, enable linking to user profile by id (default: me)

node_modules/col-activities/lib/api.js, node_modules/col-activities/lib/rest.js, node_modules/col-activities/tests/test-activities.js, node_modules/col-activities/tests/util.js, node_modules/col-core/lib/db.js, node_modules/col-rest/lib/rest/activities.js
https://jira.ets.berkeley.edu/jira/browse/COL-732
https://jira.ets.berkeley.edu/jira/browse/COL-733
For the moment these are slim payloads, returning only an id and timestamp for relevant activities. Event details can be added in as required.
=> COL-732 COL-733 Add per-asset and per-user activity APIs

public/app/assetlibrary/item/item.html, public/app/engagementindex/leaderboard/leaderboardController.js, public/app/engagementindex/leaderboard/list.html, public/app/shared/toolHrefDirective.js, public/app/shared/utilService.js, public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-737
`crossLtiSupport` (i.e., linking between LTI tools) is now a shared utility. Future cross-LTI actions might include linking to assets from profile page.
=> COL-737, link names on asset detail to profile if target tool is available

node_modules/col-activities/lib/notifications/daily.js, node_modules/col-activities/lib/notifications/weekly.js, node_modules/col-canvas/lib/api.js, node_modules/col-canvas/lib/poller.js, node_modules/col-course/lib/api.js, package.json, scripts/20170117-col629/rename_and_hide_suitec_folders.js, scripts/update_lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-752
This repointing script is more complex than its Junction cousin since we're dealing with multiple Canvases and can't provide account IDs as a configuration option. To figure out where a given tool is configured, we may need to iterate up through parent accounts.
=> COL-752 Script to update LTI configurations in Canvas

package.json
See https://docs.npmjs.com/files/package.json#license
Stop the "license" complaining in `eb-master` builds.
=> NOJIRA, fix package.json syntax with awkward license reference

public/app/assetlibrary/addbookmarklet/addbookmarklet.html, public/app/assetlibrary/addlinkcontainer/addlinkcontainer.html, public/app/assetlibrary/assetLibraryService.js, public/app/assetlibrary/backToReferrerController.js, public/app/assetlibrary/backtoreferrer.html, public/app/assetlibrary/item/assetLibraryItemController.js, public/app/assetlibrary/item/item.html, public/app/assetlibrary/uploadcontainer/uploadcontainer.html, public/app/dashboard/splash.html, public/app/dashboard/splashController.js, public/app/shared/toolHrefDirective.js, public/app/whiteboards/create/create.html, public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-769
UX Jira: https://jira.ets.berkeley.edu/jira/browse/COL-763
User on profile page, with no assets, can click to upload a new asset or learn more about bookmarklet. For these target pages to have "Back to Dashboard" we must extend the cross-tool-href paradigm by allowing `id` to carry a router-state name, as seen in `app.states.js`.
=> COL-769, when 'My Assets' is empty on profile then offer Upload / Add Link asset

bower.json
https://jira.ets.berkeley.edu/jira/browse/COL-772
Bower cache struck again, misleading me as to what major version of d3 I was using.
=> COL-772 Revert to eventdrops-compatible d3 version

scripts/update_lti.js
A small but important fix to ensure the LTI script is grabbing a real tool ID instead of a surprising number from a surprising URL.
=> NOJIRA Fix to LTI repointing script

public/app/app.bootstrap.js
https://jira.ets.berkeley.edu/jira/browse/COL-789
`assetLibraryService` expects leading `#` char. Including it in pattern match will send user to listing page, as expected.
=> COL-789, include hash in hashtag pattern match

public/app/app.bootstrap.js, public/app/assetlibrary/assetLibraryService.js, public/app/assetlibrary/backToReferrerController.js, public/app/assetlibrary/backtoreferrer.html, public/app/assetlibrary/item/assetLibraryItemController.js, public/app/assetlibrary/item/item.html, public/app/dashboard/profile.html, public/app/dashboard/profileController.js, public/app/engagementindex/leaderboard/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-816
`referringTool` is now a bundle, packaged in `app.bootstrap`. IMO, more intuitive and simplifies front-end code. The `data-referring-tool` attribute is now required.
=> COL-816, organize referringTool props prior to 'back to results' feature

public/app/app.states.js, public/app/dashboard/profile.html, public/app/dashboard/profileController.js, public/app/dashboard/search/profileSearchAutosuggestFilter.js, public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-839
Search is hard, so let's start with something simple. Put focus on search and you get list of all course users. Start typing and list narrows. Click or hit return on a user and page reloads with selected profile.  See screenshot.
Perhaps we'll end up with a more sophisticated search but... One step at a time.
=> COL-839, profile search prototype: User-only w/ autosuggest keeps you on profile page

node_modules/col-activities/lib/default.js, node_modules/col-activities/tests/test-csv.js, node_modules/col-activities/tests/test-points.js, node_modules/col-activities/tests/util.js, node_modules/col-assets/lib/api.js, node_modules/col-core/lib/db.js, scripts/20170426-col482/add_activity_enums.sql
This PR contains two commits.
The first includes a database migration and defaults for new activity types:
- `get_view_asset` (https://jira.ets.berkeley.edu/jira/browse/COL-482)
- `get_whiteboard_add_asset` (https://jira.ets.berkeley.edu/jira/browse/COL-824)
- `remix_whiteboard`, `get_remix_whiteboard` (https://jira.ets.berkeley.edu/jira/browse/COL-837)
These are awkward names but consistency in naming reciprocals (`get_` + original activity name) seems worth keeping.
The second commit includes logic and tests for `get_view_asset` only.
=> COL-482 COL-824 COL-837 New activity types

node_modules/col-canvas/lib/api.js, node_modules/col-canvas/lib/poller.js, node_modules/col-canvas/tests/model.js, node_modules/col-canvas/tests/test-poller.js, node_modules/col-canvas/tests/util.js, node_modules/col-core/lib/db.js, node_modules/col-tests/lib/util.js, node_modules/col-users/lib/api.js, node_modules/col-users/lib/constants.js, node_modules/col-users/tests/util.js, node_modules/col-whiteboards/lib/api.js, public/app/dashboard/profile.html, public/app/dashboard/profileController.js, scripts/20170501-col820/add_sections_to_users.sql
https://jira.ets.berkeley.edu/jira/browse/COL-845
Each user will have zero or more sections per course. Requires new Canvas API call: `/api/v1/courses/%d/sections?include[]=students`. When available, section names are displayed on profile page. UX tweaks may follow.
=> COL-820, canvas_course_sections added to 'users' table, displayed on profile page (Impact Studio)

node_modules/col-canvas/lib/poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-846
Superstrict validation in col-users/lib/api.js says that undefined email is OK, null email is not. Make the poller honor the contract.
=> COL-846 Do not pass null email to users API

.travis.yml, README.md, gulpfile.js, package.json
https://jira.ets.berkeley.edu/jira/browse/COL-857
Steps:
`npm test` 
or `npm test -- --grep "run tests with this pattern"`
or `npm test -- -g "run tests with this pattern"`
It's likely you'll put `NODE_ENV=test` prior to commands above.
Command line args are documented at https://mochajs.org
=> COL-857, use 'npm test' to run mocha; drop gulp-mocha

.travis.yml, README.md, gulpfile.js, package.json
https://jira.ets.berkeley.edu/jira/browse/COL-857
When we do this upgrade we must verify that mock Canvas (express) server is starting/stopping as expected. That's one theory...
=> REVERT: COL-857, use 'npm test' to run mocha; drop gulp-mocha

node_modules/col-activities/lib/default.js, node_modules/col-activities/tests/test-points.js, node_modules/col-activities/tests/test-types.js, node_modules/col-activities/tests/util.js, node_modules/col-assets/lib/api.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/util.js
This is an attempt to solve the philosophical problem in https://jira.ets.berkeley.edu/jira/browse/COL-861 without having to change too much logic or modify the database. 
I think the solution is to associate "Impact," for purposes of assets, with "active" activities rather than "passive" activities (we need better terms for this distinction).
"Impact" visualizations for individual users will continue to derive from "passive" activities.
=> COL-861 Derive asset impact score from "active" activities

public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-860
We rely on `assets.items.length` to show/hide swimlane elements. `isLoading` only controls "No matching assets..." message.
And, for now, comment out "Pinned" filter.
=> COL-860, I'm sad to say, elements must stop dancing in the swimlanes

.travis.yml, node_modules/col-assets/lib/api.js, node_modules/col-assets/lib/rest.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/util.js, node_modules/col-rest/lib/rest/assets.js, node_modules/col-tests/lib/util.js, public/app/app.states.js, public/app/assetlibrary/assetLibraryFactory.js, public/app/assetlibrary/assetLibraryService.js, public/app/assetlibrary/list/assetLibraryListController.js, public/app/assetlibrary/list/list.html, public/app/assetlibrary/search/assetLibrarySearchDirective.js, public/app/assetlibrary/search/search.html, public/app/shared/utilService.js, public/app/whiteboards/reuse/whiteboardsReuseController.js, public/assets/css/main.css
https://jira.ets.berkeley.edu/jira/browse/COL-744
List of distinct section names can be extracted from the list `users` already available in angular directive. SQL behind search now has `array_position(u.canvas_course_sections, :section)`
Initial PR #390 was closed due to no test coverage.
=> COL-744, asset-library-search gets new filter: by Section

public/app/shared/activityTimeline.css
https://jira.ets.berkeley.edu/jira/browse/COL-923
Browser permitting, the mouse cursor on activity timelines should not POINT with ONE finger but GRAB with MANY fingers.
=> COL-923 Grab, grab, grab went the cursor

public/app/app.bootstrap.js, public/app/assetlibrary/backtoreferrer.html, public/app/assetlibrary/item/item.html, public/app/assetlibrary/list/assetLibraryListController.js, public/app/assetlibrary/list/list.css, public/app/assetlibrary/list/list.html, public/app/dashboard/profile.html, public/app/dashboard/profileController.js, public/app/engagementindex/leaderboard/list.html, public/app/shared/activityTimelineEventDetails.html, public/app/shared/hashtagsFilter.js, public/app/shared/toolHrefHashtagFilter.js, public/app/shared/utilService.js, public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-924
Notes:
* Delicate refactor of toolHref logic such that the new `toolHrefHashtagFilter` can build proper links in, for example, personal descriptions.
* Because dots and dashes are allowed in hashtags, we must tweak the regex which extracts `_id` from toolHref URL.
* Hashtag followed by period (e.g., "Ready for the #world.") leads to search on keyword='world.' but user prolly wanted keyword='world'   Both hashtag-related filters are fixed. 
Bonus: `data-course` is not needed in the markup of directive.
=> COL-924, tool-href support in hashtagFilter; toolHref logic to shared utilService

node_modules/col-activities/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-931
- Only query for asset data that actually affects recalculation;
- Don't instantiate an unnecessary number of models;
- Only execute a database update when data has changed.
=> COL-931 Refactor trending calculation for performance

node_modules/col-assets/lib/api.js, node_modules/col-assets/lib/rest.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/util.js, node_modules/col-rest/lib/rest/assets.js, public/app/assetlibrary/assetLibraryFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-935
Does not include scoring yet. The `getAssets` query has unorthodox sort-by-pin_count implementation – using strictly SQL would cause a big refactor and risk (i.e., GROUP BY per SELECT criteria).
=> COL-935, AssetsAPI gets pin and unpin; getAssets query gets filter and sort per pins

node_modules/col-activities/tests/test-points.js, node_modules/col-assets/lib/api.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/test-search.js, node_modules/col-assets/tests/util.js, node_modules/col-core/lib/db.js
https://jira.ets.berkeley.edu/jira/browse/COL-949
All this to get a boolean in the asset feed. `?w=1` review recommended as ever.
Due to the required omission of instructor assets, the query for a 90th-percentile cutoff score is somewhat expensive. If there's a noticeable impact in production we may need to store and recalculate the cutoff per course.
=> COL-949 Badges: back end

node_modules/col-assets/lib/api.js, node_modules/col-assets/tests/test-search.js, node_modules/col-assets/tests/util.js, public/app/assetlibrary/assetLibraryFactory.js, public/app/assetlibrary/list/assetLibraryListController.js, public/app/assetlibrary/search/search.html, public/app/dashboard/profileController.js, public/app/shared/utilService.js, public/app/whiteboards/reuse/whiteboardsReuseController.js
https://jira.ets.berkeley.edu/jira/browse/COL-916
https://jira.ets.berkeley.edu/jira/browse/COL-919
Use case: Go to profile page, click 'My Assets > Pinned' and get ALL assets you've pinned. List will include assets uploaded/created by other users. If 'Pinned' list has 5+ assets, and you click to see more, then you'll go to Asset Library list with pre-selected filters: user: John Doe, sort by: Pinned
This PR also supports the `ORDER BY myPinned` needed by UX: https://jira.ets.berkeley.edu/jira/browse/COL-808
The next PR will include `whiteboards/reuse.html` as described in  https://jira.ets.berkeley.edu/jira/browse/COL-919
=> COL-916, hasPins support in Adv Search; wiring for whiteboardsReuseController > reuse existing asset

node_modules/col-activities/lib/api.js, node_modules/col-activities/tests/test-activities.js
https://jira.ets.berkeley.edu/jira/browse/COL-929
The trick: activities on deleted assets should be excluded, but activities with no asset should still show up. We first retrieve, then suppress.
=> COL-929 Omit activities on deleted assets from activity feed

public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-969
Another Angular lesson learned. Fortunately, QA is more concerned with having ids on _buttons_.
=> COL-969, tool-href directive cannot have dynamic id, data-ng-attr-id or otherwise

public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-977
The "400 error" described in Jira was due to pin=true attempt on an already-pinned asset. If user pins asset on his/her profile we must _always_ refresh.
=> COL-977, deal with event 'assetPinEventByMe' regardless of sortBy

public/app/assetlibrary/backtoreferrer.html, public/app/assetlibrary/item/item.html, public/app/assetlibrary/list/list.html, public/app/dashboard/profile.html, public/app/engagementindex/leaderboard/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-983
I scrutinized all other `tool-href` usages. We _should_ be back in business.
Use `w=1`
=> COL-983, tool-href don't play well with ids, part 2

public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-955
"Pin" just isn't a very long word.
=> COL-955 Asset detail buttons should not take up two parking spots in the Bootstrap grid

public/app/shared/activityTimeline.html, public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-896
Don't show 'All' zoom option unless 'All' is greater than 'Month'.
Change minimum initial zoom from 1 day to 7 days, so that 'Week' starts out as the default selection.
=> COL-896 Suppress timeline 'View By: All' when >30 days activity

public/app/dashboard/profile.css
https://jira.ets.berkeley.edu/jira/browse/COL-986
Fun fact! If the text all fits on one line, fancy flexbox `justify-content: flex-end;` controls alignment. If the text wraps, boring old `text-align: right;` must be used.
=> COL-986 Fix alignment on activity breakdown labels

public/app/whiteboards/reuse/reuse.html, public/app/whiteboards/reuse/whiteboardsReuseController.js
https://jira.ets.berkeley.edu/jira/browse/COL-993
https://jira.ets.berkeley.edu/jira/browse/COL-996
https://jira.ets.berkeley.edu/jira/browse/COL-1000
Whiteboards > add asset > use-existing
* default view (i.e., not isSearch) has new UX with Pinned Assets segregated
* search gives you standard results listing with same rules used in Asset Library search (e.g., sort by likes and you get assets with 1+ likes only)
Messaging fixes included:
=> COL-993 and COL-996, whiteboards > use-existing assets > search filter fixes and proper messaging

buildspec.yml, node_modules/col-core/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1004
CodeBuild complained with: `generate-buildspec-report.sh: Permission denied` I hope to fix that with `buildspec.yml` change.
Back-end includes the info, if file exists.
=> COL-1004, core.getVersion includes properties of buildspec-report.json

buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-1004
CodeBuild succeeded but post_build phase complained:
```
Not a git repository (or any parent up to mount point /codebuild/output)
```
[AWS docs](http://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref.html#build-env-ref-env-vars) suggest `CODEBUILD_RESOLVED_SOURCE_VERSION`. This PR checks that value and moves `generate-buildspec-report.sh` to build phase.
=> COL-1004, test CodeBuild env var: CODEBUILD_RESOLVED_SOURCE_VERSION

buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-1004
CodeBuild still ain't happy. Let's revert and put off this non-urgent issue. Sad!
For comparison, `buildspec.yml` now matches what we have on `qa` branch: https://github.com/ets-berkeley-edu/suitec/blob/qa/buildspec.yml
=> COL-1004, revert buildspec.yml to put CodePipeline back on track

public/app/dashboard/profile.css, public/app/dashboard/profile.html, public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-987
Put fixed min-height on swim lanes. In addition to herky-jerky UI, the "No matching assets" alert flickered when toggling between lanes.  This was fixed by removing the use of `isLoading`. 
The most dramatic case of empty real estate is below. This is only seen when user has zero uploaded assets. The empty space is a call to action!
----
=> COL-987, swim lanes must settle down when you toggle between empty and non-empty lanes

node_modules/col-users/lib/rest.js, public/app/dashboard/profile.html, public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1010
The `me` object (set in col-core module with `UsersAPI.getUser`) has all data we need. However, `otherUsers` list comes from `UsersAPI.getUsers` which is less rich. Two fixes here:
1. Front-end profileController wipes the slate fully clean when browsing to next user.
2. The `/users/id/:id` endpoint now relies on the richer result-set of `UsersAPI.getUser`.
=> COL-1010, use of UsersAPI.getUsers to get user data is problematic

.ebextensions/00_ami.config, .ebextensions/01_create_apache_conf.config
https://jira.ets.berkeley.edu/jira/browse/COL-1012
The new settings are, thankfully, rather simpler.
=> COL-1012 Use elbv2 settings for load balancer SSL config

config/schema.sql, node_modules/col-core/lib/db.js, node_modules/col-users/lib/constants.js, node_modules/col-users/tests/util.js, scripts/20170620-col1028/add_users_looking_for_collaborators.sql
https://jira.ets.berkeley.edu/jira/browse/COL-1028
Since this value is expected to surface across the app, including the Engagement Index, it must be added to `BASIC_USER_FIELDS` and `POINTS_USER_FIELDS`.
Suppressing this value from the feed based on Impact Studio use turns out to be impractical, as it would require too many joins to the `courses` table to check for `dashboard_url`. We're better off enforcing that logic in the front end, which always has course properties available.
=> COL-1028 User.looking_for_collaborators: database and feed

public/app/dashboard/lookingForCollaborators.html, public/app/dashboard/profile.css, public/app/engagementindex/leaderboard/leaderboardController.js, public/app/engagementindex/leaderboard/list.html, public/assets/css/main.css
https://jira.ets.berkeley.edu/jira/browse/COL-1032
Per designs, this column appears only in courses with the Impact Studio enabled; is sortable in the same way as other columns; includes a small version of the green button for other users; and duplicates the profile page's toggling functionality for oneself.
=> COL-1032 Add Collaborate column to the Engagement Index

node_modules/col-canvas/lib/api.js, node_modules/col-users/lib/api.js, public/app/dashboard/lookingForCollaborators.html, public/app/dashboard/profile.html, public/app/dashboard/profileController.js, public/app/engagementindex/leaderboard/leaderboard.html, public/app/engagementindex/leaderboard/leaderboardController.js, public/app/engagementindex/leaderboard/list.html, public/app/shared/collaborationMessageModal.css, public/app/shared/collaborationMessageModal.html, public/app/shared/collaborationMessageService.js, public/app/shared/notifications.html, public/app/shared/userFactory.js, public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-1037
Since this modal and the associated confirmation alerts may appear in any of the four tools, they're abstracted into a shared service and templates.
A back-end fix for API key authorization is in a separate commit.
=> COL-1037 Front-end modal and alerts for collaboration messages

public/app/dashboard/activityTimelineLabelDetails.html, public/app/dashboard/profileController.js
Late-breaking emendation to #541.
https://jira.ets.berkeley.edu/jira/browse/COL-1042 (design decision in https://jira.ets.berkeley.edu/jira/browse/COL-866).
1838   Extra Globe 23 Aug. 341/2   The re-use of ‘old wrappers and cut twine’, will save only a few thousands of dollars.
1882   Rep. Precious Metals (U.S. Bureau of Mint) i. 650   The water is pumped up to the stamps again for re-use.
1939   Sun (Baltimore) 21 Feb. 14/4   ‘Reprocessed’..should be applied to wool made into a fibrous state for reuse.
1970   Engin. & Med. 139   The needles..will last for hundreds of reuses.
2008   Computer Weekly 2 Sept. 27/4   Because it is costing £4.75bn to collect the LHC data, it would be profligate not to allow reuse.
=> COL-1042 reuse, n. Second or further use; an instance of this.

public/app/shared/apiError.html, public/app/shared/apiErrorController.js
https://jira.ets.berkeley.edu/jira/browse/COL-956
This goes beyond the scope of the original ticket, which was just to suppress the desktop instructions on mobile, but considering that SuiteC on iOS is now unusable without making this settings change, some explicit instructions seem called for.
=> COL-956 Add mobile-specific Safari cookie instructions

node_modules/col-activities/lib/api.js, node_modules/col-activities/tests/test-points.js
https://jira.ets.berkeley.edu/jira/browse/COL-1059
Rewarding nepotism was a feature, not a bug.
=> COL-1059, if pinner is co-owner of the asset then his collaborators get neither "pin" nor "get_pin" credit

public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1061
We expect `defaultUserPreferences` to be immutable. This bug was caused by its corruption.
=> COL-1061, reset user preferences when loading new user profile

public/app/assetlibrary/list/assetLibraryListController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1069
`isLoading = true` before subsequent Asset Library searches.
=> [QA] COL-1069, isLoading=true during subsequent searches in Asset Library

.travis.yml, README.md, bower.json, config/default.json, config/test.js, config/travis.js, gulpfile.js, node_modules/col-activities/README.md, node_modules/col-analytics/README.md, node_modules/col-assets/README.md, node_modules/col-canvas/README.md, node_modules/col-categories/README.md, node_modules/col-config/README.md, node_modules/col-core/README.md, node_modules/col-course/README.md, node_modules/col-lti/README.md, node_modules/col-rest/README.md, node_modules/col-tests/README.md, node_modules/col-users/README.md, node_modules/col-whiteboards/README.md, package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1071
Notes:
* devs might need to rename local db per changes in `default.json`
* default env for `gulp mocha`
* naming changes for Travis builds
* README changes: https://github.com/johncrossman/suitec/blob/COL-1071_renaming/README.md
=> COL-1071, travis.yml db name: suitec_travis; update db names in README; gulpfile

public/app/shared/activityTimeline.css, public/app/shared/activityTimelineDirective.js, public/app/shared/activityTimelineEventDetails.html
https://jira.ets.berkeley.edu/jira/browse/COL-904
https://jira.ets.berkeley.edu/jira/browse/COL-1070
Aside from fixing the hover behavior, restyle the d3 tooltips to look more like the Bootstrap tooltips used on the bar charts. Pointing upward means height must be fixed in advance, thus different stylings for different contexts.
=> COL-904 COL-1070 Hover and layout improvements to timeline details

config/schema.sql, node_modules/col-activities/lib/api.js, node_modules/col-activities/tests/test-activities.js, node_modules/col-activities/tests/test-points.js, node_modules/col-activities/tests/util.js, node_modules/col-assets/lib/api.js, node_modules/col-assets/lib/util.js, node_modules/col-core/lib/db.js, node_modules/col-whiteboards/lib/api.js, scripts/20170703-col1081/add_reciprocal_ids.sql
The solution to https://jira.ets.berkeley.edu/jira/browse/COL-1081 is to create `get_view_asset` activities for every `view_asset` activity that is lacking them. However, this requires an association between reciprocal activities, which doesn't currently exist in the database. This PR creates that association.
Passive activities of a `get_*` type are given a many-to-one association to their corresponding "active" activity. Going forward, this association will be tracked as part of activity creation, which in some cases involves changing the order of those creations.
Adding reciprocal ids to older activities is trickier, because we have to infer the associations based on user ids, timestamps, and other metadata. The SQL included in this PR makes a best effort at such inference. I've tested …
=> COL-1081 Add reciprocal ids to activities db table

scripts/20170703-col1081/insert_get_view_asset_activities.sql
Second and much simpler PR for https://jira.ets.berkeley.edu/jira/browse/COL-1081.
Select every `view_asset` activity not already matched to a `get_view_asset` activity; join to the `asset_users` table to get all asset owners; for each asset owner, insert a matching `get_view_asset` activity.
The query has been tested locally with good results.
=> COL-1081 Insert get_view_asset activities where not present

public/app/dashboard/profile.html, public/app/shared/toolHrefHashtagFilter.js
https://jira.ets.berkeley.edu/jira/browse/COL-1083
We use `state` to remember Impact Studio filter settings when (temporarily) navigating to Asset Library.
=> COL-1083, hashtagFilter must report 'state' to construct toolHref URL

.travis.yml, README.md, config/default.json, config/schema.sql, config/travis.js, node_modules/col-core/lib/db.js, node_modules/col-tests/lib/beforeTests.js
https://jira.ets.berkeley.edu/jira/browse/COL-951
Our dependency on Sequelize's falsely comforting "sync" behavior is removed. Instead, local and Travis test runs create their database schemas directly from SQL. This require a permissions change to the `suitec` user in test environments (see README). Devs will also have to take care to keep their local databases synced up with the latest migrations, since Sequelize will no longer be helpfully attempting to manage it for us.
=> COL-951 Remove Sequelize sync; test against db schema in source control

config/default.json, config/schema.sql, config/test.js, config/travis.js, node_modules/col-core/lib/db.js, node_modules/col-core/lib/storage.js, scripts/20170711-col1104/add_assets_aws_s3_object_key.sql
https://jira.ets.berkeley.edu/jira/browse/COL-1104
Proposal:
1. course `created_at` date must be greater than `aws.s3.suitecCutoverDate` to be eligible for AWS S3 (I will document this config if PR is merged)
1. `assets` table gets column for S3 Object Key
1. asset downloadUrl (for users) is concatenation of `aws.s3. baseDownloadUrl` (CloudFront) and S3 key.
If we're happy with this paradigm then future PRs will leverage (and test) the design.
=> COL-1104, courses db table gets 'aws_s3_object_key'; eligible-for-S3 cutoff date in config

.gitignore, config/default.json, config/travis.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/util.js, node_modules/col-core/lib/aws-sdk-factory.js, node_modules/col-core/lib/storage.js, package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1112
My attempt at factory pattern for `aws-sdk` dependency. Tests and Travis run against mock-Canvas; we need the same for AWS S3.
Fyi: https://github.com/MathieuLoutre/mock-aws-s3
=> COL-1112, AWS.S3 connector type (mock or real) is configurable; see aws-sdk-factory

node_modules/col-canvas/tests/test-poller.js, node_modules/col-canvas/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-747
The AssertionErrors in question are real errors caused by the mock Canvas not getting requests in the order it expects. For some reason they were not actually causing the tests to fail, and were logged in NODE_ENV=travis but not NODE_ENV=test. I have no explanation for this behavior.
=> COL-747 Quiet AssertionErrors from mock Canvas

.gitignore, config/default.json, config/test.js, config/travis.js, node_modules/col-assets/lib/api.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/util.js, node_modules/col-canvas/lib/poller.js, node_modules/col-canvas/tests/test-poller.js, node_modules/col-core/lib/db.js, node_modules/col-core/lib/storage.js, node_modules/col-tests/lib/util.js, node_modules/col-whiteboards/lib/api.js, package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1104
* download_url remains but construction might use new CloudFront + S3 convention
* dev, test and travis have distinct `s3-bucket` on localhost
* poller is sensitive to `asset.aws_s3_object_key`
=> COL-1104, storage of assets > downloadURL is legacy Canvas or CloudFront + S3 Object Key

node_modules/col-assets/lib/rest.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-core/lib/db.js, node_modules/col-core/lib/storage.js, node_modules/col-whiteboards/lib/api.js, public/app/assetlibrary/item/assetLibraryItemController.js, public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-1097
We might circumvent the need for CloudFront by maintaining our own lightweight proxy. The AWS S3 module makes it easy to get a handle on the IO-stream and file metadata. If this approach is fruitful then we can eliminate `download_url` column after migration off of Canvas Files API.
=> COL-1097, download assets via proxy to S3.getObject

package.json, scripts/install-locally.sh
https://jira.ets.berkeley.edu/jira/browse/COL-1136
* reorder elements of package.json to put important bits on top (matches best practice, as far as I can tell) 
* The script change silences `npm install`
=> COL-1136, upgrade aws-sdk; shuffle package.json

.ebextensions/04_download_local_configuration.config, .travis.yml, config/default.json, config/test.js, config/travis.js, node_modules/col-analytics/lib/api.js, node_modules/col-analytics/lib/caliper.js, package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1122
We work around the private status of the caliper.js library by (for now) installing from a fork under a developer account. Access is granted via https/API key rather than ssh so that both Travis and Elastic Beanstalk can use it. (Elastic Beanstalk downloads the key from S3; Travis has been given the key in an environment variable.)
With this change, developer machines, etc. wishing to run `npm install` will need to either copy the ~/.netrc file from S3 or use a Github account with "collaborator" status on the personal caliper-js fork.
=> COL-1122 Add caliper-js dependency and wrapping analytics module

buildspec.yml
See "Build Environment Compute Types" at http://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref.html
preview-service is happy with the same setting:
https://github.com/ets-berkeley-edu/suitec-preview-service/blob/master/buildspec.yml
=> NOJIRA, SuiteCLand gets proper ComputeType in buildspec

config/default.json, node_modules/col-core/lib/storage.js
https://jira.ets.berkeley.edu/jira/browse/COL-573
If we resurrect the CloudFront design then `baseDownloadUrl` might return. (Storage code will get better test coverage soon.)
=> COL-573, fix failing file downloads (variable naming); remove obsolete baseDownloadUrl

config/default.json, config/travis.js, node_modules/col-analytics/lib/caliper.js, node_modules/col-analytics/tests/test-caliper.js, node_modules/col-analytics/tests/util.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-lti/tests/util.js, node_modules/col-tests/lib/beforeTests.js, scripts/caliper-listener.js
https://jira.ets.berkeley.edu/jira/browse/COL-1124
- Instead of sending events via the caliper-js sensor, which seems to be incompletely implemented, handle the request code ourselves.
- In dev environments, the `caliper-listener.js` script can be run (instructions included in script) to receive events as they're fired off.
- For test runs, a mock Caliper endpoint is set up on the pattern of our mock Canvas server to run assertions on generated events.
=> COL-1124 Caliper event transmission, test coverage

node_modules/col-analytics/lib/caliper.js, node_modules/col-analytics/tests/test-caliper.js, node_modules/col-analytics/tests/util.js, node_modules/col-assets/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-1128
'Disliking' is of course not supported in the current UX, but we may as well shoot for consistency.
Like and dislike events generate a Caliper AnnotationEntity with id derived from the asset and user. 'Unliking' (i.e., removing a previous like or dislike) is then modeled as a Caliper 'remove' action taking that AnnotationEntity as its object.
=> COL-1128 Caliper instrumentation: asset (dis/un)liking

node_modules/col-analytics/tests/test-caliper.js, node_modules/col-assets/lib/migrate.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/test-migrate.js, node_modules/col-assets/tests/util.js, node_modules/col-canvas/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1085
The migrate_assets script will download file to temp dir, upload to S3 and record resulting `s3://` address. The `mockFileUpload` op in our test utils did not produce a valid download_url therefore I extended the test util and our migrate script to recognize `file://` URIs. (Note: temp downloads are timestamped to avoid collisions.)
=> COL-1085, migration script > Canvas filesystem to Amazon S3

.eslintrc.yml, node_modules/col-analytics/tests/test-caliper.js, package.json, scripts/move_canvas_files_to_amazon_s3.js
https://jira.ets.berkeley.edu/jira/browse/COL-1154
https://jira.ets.berkeley.edu/jira/browse/COL-1156
* We want to migrate deleted assets in case they are later undeleted 
* The SuiteC db will certainly have invalid Canvas URLs (especially in test environments); a "failures" CSV file makes sense
* Finally, the CSVs generated by this script are important and we want the executor of the script to be well aware of their location. Thus, we now require `--csv_directory`
=> COL-1156, Migrate deleted assets, properly record failures and 'csv_directory' arg is now required

public/app/whiteboards/board/whiteboardsBoardDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1159
whiteboardDirective is not impressed with our half-baked `s3://` protocol.  We must construct URL as seen on asset detail page > download button.
=> COL-1159, if asset image is in Amazon S3 then use /download route to grab it

config/default.json
https://jira.ets.berkeley.edu/jira/browse/COL-1158
Caliper-related changes to SuiteC analytics config require Mixpanel to be turned off by default. Turning it back on locally in suitec-qa and suitec-prod will be covered in release-specific instructions.
=> COL-1158 Disable Mixpanel in default configuration

node_modules/col-whiteboards/data/whiteboardToPng.js
https://jira.ets.berkeley.edu/jira/browse/COL-1157
It's not clear to me how we were ever getting white backgrounds without this explicit setting, but we can only fit so many mysteries into one day.
=> COL-1157 Force white background on whiteboard PNG exports

public/app/whiteboards/board/whiteboardsBoardDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1166
It's unknown why our websocket handshake is currently failing on AWS, but until we get around to investigating, we may as well tell our code not to attempt and error.
=> COL-1166 Tell socket.io not to attempt failing websocket handshake

node_modules/col-assets/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-553
If asset is deleted or hidden then `/asset/:id` and `/assets/:assetId/download` will return 404, "The requested asset has been removed".
=> COL-553, if asset isDeletedOrHidden then deny attempt to view/download

scripts/20170831-col1184/deactivate_deleted_course_sites.sql
https://jira.ets.berkeley.edu/jira/browse/COL-1184
You can verify the deleted-ness of these course sites with:
* https://bcourses.berkeley.edu/api/v1/courses/1460736/users
* https://bcourses.berkeley.edu/api/v1/courses/1461213/users
* https://bcourses.berkeley.edu/api/v1/courses/1461536/users
* https://bcourses.berkeley.edu/api/v1/courses/1462149/users
* https://bcourses.berkeley.edu/api/v1/courses/1462239/users
* https://bcourses.berkeley.edu/api/v1/courses/1462466/users
* https://bcourses.berkeley.edu/api/v1/courses/1462469/users
* https://bcourses.berkeley.edu/api/v1/courses/1462815/users
=> COL-1184, poller does not deactivate deleted course sites; for now, deactivate them the hard way

node_modules/col-activities/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1183
Keep calm. ActivitiesAPI.deleteActivity is used to remove any previous activities that may match certain criteria - for example, as part of creating a like activity, any previous likes are removed. Failure to find a match is quite in the normal course of business and doesn't need to be logged.
=> COL-1183 Failure to find activity during delete request is no cause for alarm

public/app/assetlibrary/item/assetLibraryItemController.js, public/app/shared/utilService.js
https://jira.ets.berkeley.edu/jira/browse/COL-1196
When it comes to `download_url` and `video_url`, SuiteC server-side is a proxy to Amazon S3.
=> COL-1196, video_url, on asset detail view, is preview_metadata.converted_video or /assets/:id/download

node_modules/col-assets/lib/api.js, node_modules/col-assets/lib/rest.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1194
Putting this logic at `/asset/:asset_id` and `/download/...` was a bit tougher than expected. I use a db query instead of WhiteboardsAPI call, which I believe would be more expensive. (See `badgeEligibleAssetsQuery` for similar decision.)
=> COL-1194, hidden assets can be viewed by only collaborators and admins

config/default.json, config/test.js, config/travis.js, node_modules/col-assets/lib/api.js, node_modules/col-assets/tests/test-assets.js, node_modules/col-assets/tests/test-migrate.js, node_modules/col-assets/tests/util.js, node_modules/col-canvas/lib/api.js, node_modules/col-canvas/tests/model.js, node_modules/col-canvas/tests/util.js, node_modules/col-core/lib/storage.js, node_modules/col-tests/lib/util.js, node_modules/col-whiteboards/lib/api.js, node_modules/col-whiteboards/tests/util.js, scripts/move_canvas_files_to_amazon_s3.js
https://jira.ets.berkeley.edu/jira/browse/COL-1108
* the `move_canvas_files_to_amazon_s3.js` script is still usable
* Canvas assignment integration should not be impacted
* all obsolete code removed, I hope
=> COL-1108, post S3-migration: remove code associated with file storage in Canvas

scripts/refresh-data.sh
In the fast-paced world of copy-and-paste, I don't want prod configs to accidentally land in `${dest_suitec}.json`.
=> NOJIRA, refresh-data.sh > exit if dest_host URL contains '-prod'

.ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/COL-1218
Rather than put a cap on the number of restarts, always restart unless the app stays up for less than 10 seconds.
=> COL-1218 Make forever truly forever

node_modules/col-activities/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1241
These users don't show up in the user feed, meaning that d3-force can't match them up and goes on to lose its mind.
=> COL-1241 Exclude inactive users from interactions feed

public/app/dashboard/activityNetworkDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1247
Follow-up to #685. `scope.user` is constrained to appear near the center of the diagram. `scope.focalUser` does not need this constraint; it just needs the larger bubble size accounted for.
=> COL-1247 Activity network: follow-up boundary handling for focal user

public/app/dashboard/profileController.js, public/app/shared/userFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-1291
On server side, at `/users/leaderboard`, we have:
```
// Track the request unless explicitly told otherwise.
var track = true;
if (CollabosphereUtil.getBooleanParam(req.query.track) === false) {
track = false;
}
...
```
=> COL-1291, do not record 'Get engagement index' event when user hits profile page

node_modules/col-analytics/lib/rest.js, node_modules/col-analytics/lib/util.js, node_modules/col-analytics/tests/test-event.js, node_modules/col-analytics/tests/util.js, node_modules/col-rest/lib/api.js, node_modules/col-rest/lib/rest/events.js
https://jira.ets.berkeley.edu/jira/browse/COL-1301
In preparation for client-side cutover, we make `/api/track` available. The long list of optional object-id args seems cleaner than a more obscure `object` and `contextObject`.
=> COL-1301, rest endpoint to track events, accepting optional id params

public/app/whiteboards/board/whiteboardsBoardDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1317
Bug caused by use of `?track=false` on URL with preexisting args.
=> COL-1317, append 'track' to URL with proper query arg connector

public/app/shared/analyticsService.js
https://jira.ets.berkeley.edu/jira/browse/COL-1314
As promised, I briefly investigated "drops" in event tracking (eg, EI searches). This PR adds `$q` usage ([Angular service](https://docs.angularjs.org/api/ng/service/$q) runs functions async) which seems reliable in local testing. This might well reduce "drops".
=> COL-1314, analyticsService.track invokes async $q wrapping trackEvent

node_modules/col-users/lib/api.js, public/app/dashboard/activityNetwork.html, public/app/dashboard/activityNetworkDirective.js, public/app/dashboard/profile.css, public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1326
- Network viewport size increases for large classes;
- For users where last_activity is null, created_at is used to determine whether they count as "recent";
- Alpha decay is increased so the simulation settles down a little faster.
=> COL-1326 Activity network performance tweaking

node_modules/col-activities/package.json, node_modules/col-analytics/package.json, node_modules/col-assets/package.json, node_modules/col-canvas/package.json, node_modules/col-categories/package.json, node_modules/col-config/package.json, node_modules/col-core/package.json, node_modules/col-course/package.json, node_modules/col-lti/package.json, node_modules/col-rest/package.json, node_modules/col-tests/package.json, node_modules/col-users/package.json, node_modules/col-whiteboards/package.json, package.json
Used `./scripts/bump-version.sh  minor`
Fyi, prod is currently 2.7.0: https://app-prod.ets-berkeley-suitec.net/api/version
=> [QA] NOJIRA, qa branch of SuiteC > version bumped to 2.8.0

.ebextensions/01_create_apache_conf.config, apache/suitec.template, bower.json, node_modules/col-core/lib/server.js, package.json, public/app/whiteboards/board/whiteboardsBoardDirective.js, public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-1341
* `proxy_wstunnel_module` needs to happen in `VirtualHost *:443`
* upgrade related `socket.io` dependencies (server and client)
* minimal browser console logging confirms successful `websocket` connect  
`suitec-dev` is currently running code from my branch (ie, this PR). To test, open whiteboard on https://ucberkeley.beta.instructure.com/courses/1456107/external_tools/56484 and open browser console.
cc: @paulkerschen
=> COL-1341, real websocket connection; bumped version on socket.io dependencies

node_modules/col-activities/package.json, node_modules/col-analytics/package.json, node_modules/col-assets/package.json, node_modules/col-canvas/package.json, node_modules/col-categories/package.json, node_modules/col-config/package.json, node_modules/col-core/package.json, node_modules/col-course/package.json, node_modules/col-lti/package.json, node_modules/col-rest/package.json, node_modules/col-tests/package.json, node_modules/col-users/package.json, node_modules/col-whiteboards/package.json, package.json
This patch release has websockets-related work. We are recalibrating version number on qa branch because this is a patch release.  `master` branch will remain at 2.9.0.
=> NOJIRA, set qa branch version to 2.8.3 (patch release)

package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1357
=> COL-1357, security vulnerability in mime < 1.4.1; upgrade to 1.6.0

package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1358
v6.1.6 has been patched according to https://node-postgres.com/announcements
=> COL-1358, bump node-postgres to 6.1.6 (security vulnerability)

package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1398
=> COL-1398, no more eslint and bower security vulnerabilities, for now
