- node_modules/col-core/lib/db.js
This adds in the model as sketched out yesterday. It currently supports:
- Canvas
- Courses
- Users
- Activities (and their types)
- Assets (and their categories)
- Comments
> Added the initial model

- bower.json
- node_modules/col-lti/lib/api.js
- node_modules/col-lti/lib/rest.js
- public/app/assetlibrary/addbookmarklet/addbookmarklet.html
- public/app/assetlibrary/addbookmarklet/assetLibraryAddBookmarkletController.js
- public/app/assetlibrary/addlink/addlink.html
- public/app/shared/utilService.js
- public/assets/css/bookmarklet.css
- public/assets/css/main.css
- public/assets/js/bookmarklet-init.js
- public/assets/js/bookmarklet.js
- public/bookmarklet.html
- Add better styling to the bookmarklet
- Add ability to close modal
- Prevent modal from being opened multiple time
- Show success notification and link back to Asset Library
- Improve clickability of items from the page
- Show empty messages when no items can be found on the page
https://jira.ets.berkeley.edu/jira/browse/COL-44
> COL-44 - Set up bookmarklet structure

- node_modules/col-canvas/lib/api.js
- node_modules/col-core/lib/db.js
- node_modules/col-course/lib/api.js
- node_modules/col-lti/tests/test-lti.js
- node_modules/col-users/lib/api.js
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-29
> COL-29 - Follow up on outstanding code review

- node_modules/col-core/lib/constants.js
- node_modules/col-lti/lib/api.js
Admin user cannot view tool
https://jira.ets.berkeley.edu/jira/browse/COL-82
> COL-82 - Admin user cannot view tool

- node_modules/col-assets/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-376
> COL-376 - Tmp space fills up

- node_modules/col-lti/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6247
> CLC-6247 - Enabling Collabosphere LTI Tool at Account Level in bCourses

- public/app/whiteboards/board/whiteboardsBoardDirective.js
- public/app/whiteboards/edit/whiteboardsEditController.js
- public/app/whiteboards/list/whiteboardsListController.js
https://jira.ets.berkeley.edu/jira/browse/COL-340
One UX question: this does make it easier for a user to inadvertently lose access to a whiteboard. Is it worth a confirmation dialog?
> COL-340 When user removes self from whiteboard, close and refresh list

- node_modules/col-whiteboards/lib/api.js
- node_modules/col-whiteboards/tests/test-whiteboards.js
- node_modules/col-whiteboards/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-262
> COL-262 Do not include current user in online whiteboard users count

- public/assets/js/bookmarklet.js
https://jira.ets.berkeley.edu/jira/browse/COL-334
> COL-334 Fix background image retrieval in bookmarklet

- public/app/engagementindex/leaderboard/leaderboard.html
- public/app/engagementindex/leaderboard/list.css
- public/app/engagementindex/leaderboard/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-246
> COL-246 Surface points configuration to students who don't share scores

- public/app/assetlibrary/iconbar/AssetLibraryIconBarDirective.js
- public/app/assetlibrary/iconbar/iconbar.css
- public/app/assetlibrary/iconbar/iconbar.html
- public/app/assetlibrary/list/list.css
- public/app/assetlibrary/list/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-127
> COL-127 - Make iconbar views and comments clickable

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
- node_modules/col-core/lib/db.js
- node_modules/col-whiteboards/tests/util.js
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.html
- scripts/20160525-col378/add_element_asset_id_to_asset_whiteboard_elements.sql
- scripts/20160525-col378/populate_element_asset_id.js
https://jira.ets.berkeley.edu/jira/browse/COL-378
> COL-378 Allow non-admin users to delete associated assets with no interactions

- public/app/assetlibrary/search/search.html
- public/app/whiteboards/reuse/reuse.html
https://jira.ets.berkeley.edu/jira/browse/COL-352
Note that the changes are mostly indentation.
> COL-352 Fix nested form in asset reuse modal

- config/default.json
https://jira.ets.berkeley.edu/jira/browse/COL-412
> COL-412, canvasPoller.enabled by default

- node_modules/col-activities/lib/api.js
- node_modules/col-assets/lib/api.js
- node_modules/col-canvas/lib/poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-403
> COL-403 Include asset_id when saving comment activities

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/lib/rest.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
- node_modules/col-core/lib/db.js
- node_modules/col-rest/lib/rest/assets.js
- public/app/assetlibrary/addlink/addlink.css
- public/app/assetlibrary/addlink/addlink.html
- public/app/assetlibrary/addlink/assetLibraryAddLinkController.js
- public/app/assetlibrary/assetLibraryFactory.js
- public/app/assetlibrary/upload/upload.css
- public/app/assetlibrary/upload/upload.html
- public/app/whiteboards/addlinkmodal/whiteboardsAddLinkController.js
- public/index.html
- scripts/20160801-col382/add_list_to_assets.sql
https://jira.ets.berkeley.edu/jira/browse/COL-382
> COL-382 - Don't automatically add whiteboard assets to asset library

- node_modules/col-activities/lib/default.js
- node_modules/col-core/lib/constants.js
- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-406
https://jira.ets.berkeley.edu/jira/browse/COL-407
Like other activity types, these are viewable and modifiable through the Engagement Index.
Tested locally, but no integration tests added as our suite currently doesn't cover whiteboard actions through websockets.
> COL-406 COL-407 Add new whiteboard-related activity types

- scripts/20160812-col429/add_activity_enums.sql
https://jira.ets.berkeley.edu/jira/browse/COL-429
> COL-429 Postgres migration for new activity types and objects

- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-433
> COL-433 Fix error logging in whiteboards

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/model.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-core/lib/db.js
- node_modules/col-course/lib/api.js
- node_modules/col-course/lib/rest.js
- node_modules/col-course/tests/test-course.js
- node_modules/col-course/tests/util.js
- node_modules/col-rest/lib/api.js
- node_modules/col-rest/lib/rest/course.js
- public/app/assetlibrary/assetLibraryCourseFactory.js
- public/app/assetlibrary/categories/assetLibraryCategoriesController.js
- public/app/assetlibrary/categories/categories.html
- public/index.html
- scripts/20160818-col439/add_course_enable_assignment_sync_from.sql
https://jira.ets.berkeley.edu/jira/browse/COL-439
> COL-439 Add per-course toggle for Canvas assignment sync

- public/app/assetlibrary/categories/categories.html
https://jira.ets.berkeley.edu/jira/browse/COL-446
> [QA] COL-446 Improve messaging in Asset Library sync option

- public/app/assetlibrary/categories/categories.html
https://jira.ets.berkeley.edu/jira/browse/COL-446
Master-branch version of #157.
> COL-446 Improve messaging in Asset Library sync option

- scripts/migrate_assets.js
https://jira.ets.berkeley.edu/jira/browse/COL-449
Migrate file knowing that temp dir creation succeeded. Significant change is:
```
var downloadDir = path.join(os.tmpdir(), processStartTime.toString());
fs.stat(downloadDir, function(err, stat) {
...
```
Add `?w=1` to URL to ignore whitespace in diff.
> COL-449, migrate_assets.js script creates dedicated temp dir for file downloads

- node_modules/col-canvas/lib/poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-453
> COL-453 Don't attempt to double-delete temp files when processing Canvas assignments

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/lib/api.js
- node_modules/col-core/package.json
- node_modules/col-core/tests/test-status.js
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-307
`/api/status` will have:
```
{
app: true,
db: true,
version: "1.6",
...
}
```
> COL-307, /api/status now reports app version info

- email-templates/_shared/style.css
- email-templates/weekly/html.ejs
- email-templates/weekly/style.scss
https://jira.ets.berkeley.edu/jira/browse/COL-468
See JIRA for what all we're fixing.
> COL-468 Weekly email: miscellaneous front-end fixes

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-core/lib/api.js
- node_modules/col-core/tests/test-status.js
https://jira.ets.berkeley.edu/jira/browse/COL-457
> COL-457 Add a poller health check to /api/status

- node_modules/col-activities/lib/notifications/weekly.js
https://jira.ets.berkeley.edu/jira/browse/COL-478
https://jira.ets.berkeley.edu/jira/browse/COL-479
Include deleted assets in point calculations, but ensure they don't get featured in the weekly email.
> COL-478 COL-479 Weekly email: better handling for deleted assets

- node_modules/col-activities/lib/notifications/weekly.js
https://jira.ets.berkeley.edu/jira/browse/COL-478
https://jira.ets.berkeley.edu/jira/browse/COL-479
QA version of #172.
> [QA] COL-478 COL-479 Weekly email: better handling for deleted assets

- email-templates/weekly/html.ejs
https://jira.ets.berkeley.edu/jira/browse/COL-477
> COL-477 Weekly email: replace 'leaderboard' with 'Engagement Index'

- email-templates/weekly/html.ejs
https://jira.ets.berkeley.edu/jira/browse/COL-477
QA version of #174.
> [QA] COL-477 Weekly email: replace 'leaderboard' with 'Engagement Index'

- email-templates/_shared/style.css
- email-templates/weekly/style.scss
https://jira.ets.berkeley.edu/jira/browse/COL-476
QA version of #176.
> [QA] COL-476 Weekly email: use darker light gray

- node_modules/col-activities/lib/default.js
Follow-up PR for https://jira.ets.berkeley.edu/jira/browse/COL-407.
> COL-407 Default whiteboard activities to zero points

- node_modules/col-activities/lib/default.js
QA version of #181.
Follow-up PR for https://jira.ets.berkeley.edu/jira/browse/COL-407.
> [QA] COL-407 Default whiteboard activities to zero points

- deploy/deploy.sh
https://jira.ets.berkeley.edu/jira/browse/COL-365
https://jira.ets.berkeley.edu/jira/browse/COL-486
The script will:
* cd to base dir of local repo
* log important stuff to time-stamped log file
* validate, report errors (e.g., no such tag)
* give user more info via console
* pause before blowing away local changes
> COL-365, deploy script now supports deploy-by-tag

- node_modules/col-whiteboards/data/whiteboardToPng.js
- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-383
> COL-383 Better buffering for whiteboard PNG export

- node_modules/col-assets/lib/api.js
- node_modules/col-whiteboards/lib/api.js
- scripts/20161011-col509/update_whiteboard_asset_previews.js
https://jira.ets.berkeley.edu/jira/browse/COL-509
> COL-509 Verify asset previews available before exporting whiteboard

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
Friday Oct 14: SuiteC v1.6.2 release
> [QA] NOJIRA, bump package version to 1.6.2

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
The next feature release will be v1.7.0.
> NOJIRA, bump package version to 1.7.0 (master branch)

- node_modules/col-assets/lib/api.js
- node_modules/col-whiteboards/lib/api.js
- scripts/20161011-col509/update_whiteboard_asset_previews.js
https://jira.ets.berkeley.edu/jira/browse/COL-509
QA version of #192.
> [QA] COL-509 Verify asset previews available before exporting whiteboard

- node_modules/col-activities/lib/notifications/daily.js
- node_modules/col-activities/lib/notifications/weekly.js
- node_modules/col-activities/tests/test-daily.js
- node_modules/col-activities/tests/test-weekly.js
- node_modules/col-core/lib/db.js
- node_modules/col-course/lib/api.js
- node_modules/col-course/lib/rest.js
- node_modules/col-course/tests/test-course.js
- node_modules/col-course/tests/util.js
- node_modules/col-rest/lib/rest/course.js
- public/app/assetlibrary/categories/assetLibraryCategoriesController.js
- public/app/engagementindex/leaderboard/leaderboardController.js
- public/app/engagementindex/leaderboard/share.html
- public/app/shared/courseFactory.js
- public/index.html
- scripts/20161012-col492/add_course_notification_settings.sql
https://jira.ets.berkeley.edu/jira/browse/COL-492
> COL-492 Allow course admins to toggle notification emails

- node_modules/col-activities/lib/notifications/daily.js
- node_modules/col-activities/lib/notifications/weekly.js
- node_modules/col-activities/tests/test-daily.js
- node_modules/col-activities/tests/test-weekly.js
- node_modules/col-core/lib/db.js
- node_modules/col-course/lib/api.js
- node_modules/col-course/lib/rest.js
- node_modules/col-course/tests/test-course.js
- node_modules/col-course/tests/util.js
- node_modules/col-rest/lib/rest/course.js
- public/app/assetlibrary/categories/assetLibraryCategoriesController.js
- public/app/engagementindex/leaderboard/leaderboardController.js
- public/app/engagementindex/leaderboard/share.html
- public/app/shared/courseFactory.js
- public/index.html
- scripts/20161012-col492/add_course_notification_settings.sql
https://jira.ets.berkeley.edu/jira/browse/COL-492
QA version of #195.
> [QA] COL-492 Allow course admins to toggle notification emails

- node_modules/col-whiteboards/lib/api.js
- scripts/20161011-col509/update_whiteboard_asset_previews.js
https://jira.ets.berkeley.edu/jira/browse/COL-509
Follow-up to #192.
> COL-509 Fix for Lodash 3 compatibility

- node_modules/col-whiteboards/lib/api.js
- scripts/20161011-col509/update_whiteboard_asset_previews.js
https://jira.ets.berkeley.edu/jira/browse/COL-509
QA version of follow-up PR #198.
> [QA] COL-509 Fix for Lodash 3 compatibility

- README.md
https://jira.ets.berkeley.edu/jira/browse/COL-529
Includes:
* renaming
* favoring of `createuser` and `createdb` (PostegreSQL)
> COL-529, update and tidy SuiteC README.md

- deploy/canvas-integration-SQL-generator.sh
https://jira.ets.berkeley.edu/jira/browse/COL-531
SuiteC code has:
```
'oauth_consumer_key': Joi.string().alphanum().length(32).required(),
```
This is overly restrictive but we'll comply – see change in `generate_token()`.
Bonus: generated file uses `name`
> COL-531, comply with SuiteC's alphanum restriction on LTI key & secret

- node_modules/col-assets/lib/api.js
- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-527
> COL-527 Show asset usage in exported whiteboards

- README.md
- docs/configuration.md
- docs/deployment.md
https://jira.ets.berkeley.edu/jira/browse/COL-536
Lastly, add clarity to instructions on Apache config and move to `docs/configuration.md`.
> COL-536, move and expand steps to set up Apache config

- README.md
- deploy/deploy.sh
- docs/deployment.md
https://jira.ets.berkeley.edu/jira/browse/COL-540
Deploy script's usage info and `docs/deployment.md` work hand-in-hand.
> COL-540, SuiteC docs/deployment.md has been corrected

- node_modules/col-activities/tests/test-points.js
- node_modules/col-activities/tests/util.js
- node_modules/col-assets/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-505
> COL-505 Do not award points for assets not included in library

- public/app/assetlibrary/categories/categories.html
https://jira.ets.berkeley.edu/jira/browse/COL-534
> COL-534 Improve assignment sync messaging

- config/default.json
Also, honor the alphabet.
https://jira.ets.berkeley.edu/jira/browse/COL-530
> COL-530 Disable email by default

- public/app/assetlibrary/edit/assetLibraryEditController.js
https://jira.ets.berkeley.edu/jira/browse/COL-523
I'm no ui-router expert but this seems to do the job.
http://stackoverflow.com/questions/21714655/reloading-current-state-refresh-data
> COL-523 Reload asset state after editing details

- node_modules/col-canvas/lib/poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-551
A few hours of study on assignment submissions, the poller code and file naming leads to a one-word rebranding.
> COL-551, asset downloads (assignment submissions) are branded 'suitec'

- README.md
- bower.json
- docs/deployment.md
- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-562
> COL-562, update Git URL in package.json files, README, etc.

- public/app/assetlibrary/item/assetLibraryItemController.js
https://jira.ets.berkeley.edu/jira/browse/COL-346
Goes together with https://github.com/ets-berkeley-edu/suitec-preview-service/pull/2
> COL-346 Use embeddable asset URLs if provided in preview metadata

- apache/apache.js
- apache/suitec.template
- docs/configuration.md
https://jira.ets.berkeley.edu/jira/browse/COL-575
This is for developer workstations. We'll need to do similar work on dev, qa and prod servers - see https://jira.ets.berkeley.edu/jira/browse/COL-578
> COL-575, rename apache/collabosphere.conf to apache/suitec.conf

- public/app/assetlibrary/categories/categories.html
https://jira.ets.berkeley.edu/jira/browse/COL-534
> COL-534 Clarify that synced assignments appear as categories

- public/app/assetlibrary/categories/categories.html
https://jira.ets.berkeley.edu/jira/browse/COL-561
> COL-561 Cancel the can can

- public/app/assetlibrary/item/assetLibraryItemController.js
https://jira.ets.berkeley.edu/jira/browse/COL-346
QA version of #223.
> [QA] COL-346 Use embeddable asset URLs if provided in preview metadata

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/model.js
- node_modules/col-canvas/tests/test-poller.js
- scripts/20161109-col517/remove_old_discussion_activities.js
https://jira.ets.berkeley.edu/jira/browse/COL-473
https://jira.ets.berkeley.edu/jira/browse/COL-533
https://jira.ets.berkeley.edu/jira/browse/COL-537
https://jira.ets.berkeley.edu/jira/browse/COL-541
QA version of #202, #208, #209 and #215.
> [QA] COL-473 COL-533 COL-537 COL-541 Track threaded Canvas discussions in Engagement Index

- node_modules/col-canvas/lib/poller.js
- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-416
https://jira.ets.berkeley.edu/jira/browse/COL-551
Master PRs: #205 #219
> [QA] COL-416: download assets; COL-551: download file naming

- deploy/start.sh
- deploy/stop.sh
https://jira.ets.berkeley.edu/jira/browse/COL-514
Give start.sh and stop.sh the same behavior as deploy.sh and install-locally.sh.
> COL-514 Use correct working directory in start and stop scripts

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-480
> COL-480 Do not increment view count when creator views asset

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
> NOJIRA, bump SuiteC to v1.6.3

- node_modules/col-rest/lib/rest/whiteboards.js
- node_modules/col-whiteboards/lib/api.js
- node_modules/col-whiteboards/lib/rest.js
- node_modules/col-whiteboards/tests/test-whiteboards.js
- node_modules/col-whiteboards/tests/util.js
- public/app/whiteboards/board/board.html
- public/app/whiteboards/board/whiteboardsBoardDirective.js
- public/app/whiteboards/whiteboardsFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-441
> COL-441 Admin-only whiteboard deletion

- deploy/deploy.sh
- deploy/start.sh
- deploy/stop.sh
master PRs: #236 #237
I'm putting this to `qa` branch only because we're manually patching prod with these changes and I'd like future emergency releases, if any, to formally deploy the change.
> [QA] NOJIRA, remove start.sh from deploy.sh; post-deploy tasks might require downtime

- deploy/deploy.sh
https://jira.ets.berkeley.edu/jira/browse/COL-582
Lesson learned from the school of hard knocks.
> COL-582, deploy script gets npm cache clean and better find/rm statement 

- docs/configuration.md
- docs/deployment.md
https://jira.ets.berkeley.edu/jira/browse/COL-588
Modified deploy instructions given new [scripts in suitec-ops](https://github.com/ets-berkeley-edu/suitec-ops).
> COL-588, update SuiteC deployment.md according to changes in suitec-ops/scripts

- public/app/assetlibrary/iconbar/assetLibraryIconBarController.js
- public/app/assetlibrary/iconbar/iconbar.html
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.html
- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/assetlibrary/list/list.html
- public/app/assetlibrary/search/assetLibrarySearchDirective.js
- public/app/assetlibrary/upload/upload.html
- public/app/engagementindex/leaderboard/leaderboardController.js
- public/app/engagementindex/leaderboard/share.html
- public/app/engagementindex/points/points.html
- public/app/engagementindex/points/pointsController.js
- public/app/whiteboards/board/board.html
- public/app/whiteboards/board/whiteboardsBoardDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-564
> COL-564 Screenreader alerts for asset library actions

- node_modules/col-activities/lib/api.js
- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-course/lib/api.js
- node_modules/col-course/lib/rest.js
- node_modules/col-course/tests/test-course.js
- node_modules/col-course/tests/util.js
- node_modules/col-rest/lib/rest/course.js
- public/app/assetlibrary/list/list.html
- public/app/engagementindex/leaderboard/leaderboard.html
- public/app/shared/courseFactory.js
- public/app/shared/syncDisabledController.js
- public/app/shared/syncdisabled.css
- public/app/shared/syncdisabled.html
- public/app/whiteboards/list/list.html
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-524
> COL-524 Disable Canvas polling for a course after 90 days of inactivity; admins can re-enable

- node_modules/col-assets/lib/api.js
- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-592
> COL-592 Deduplicate assignment submissions in Asset Library

- node_modules/col-core/lib/db.js
- node_modules/col-rest/lib/rest/whiteboards.js
- node_modules/col-whiteboards/lib/api.js
- node_modules/col-whiteboards/lib/rest.js
- node_modules/col-whiteboards/tests/test-whiteboards.js
- node_modules/col-whiteboards/tests/util.js
- public/app/whiteboards/board/board.css
- public/app/whiteboards/board/board.html
- public/app/whiteboards/board/whiteboardsBoardDirective.js
- public/app/whiteboards/edit/edit.html
- public/app/whiteboards/edit/whiteboardsEditController.js
- public/app/whiteboards/list/list.html
- public/app/whiteboards/list/whiteboardsListController.js
- public/app/whiteboards/search/search.html
- public/app/whiteboards/search/whiteboardsSearchDirective.js
- public/app/whiteboards/whiteboardsFactory.js
- public/assets/css/main.css
- scripts/20161212-col597/add_whiteboards_deleted_at.sql
https://jira.ets.berkeley.edu/jira/browse/COL-597
See JIRA for new behavior. The vast majority of new code has to do with retrieving and restoring the deleted boards.
> COL-597 Allow any whiteboard member to delete boards; admins can restore

- docs/deployment.md
Pull script enhancements in prod _after_ they're road-tested in dev & qa.
> NOJIRA, prod suitec-ops will be updated deliberately, not automatically

- scripts/20160910-col398/add_category_visible.sql
- scripts/20160910-col398/remove_enable_assignment_sync_from.sql
- scripts/20161121-col497/default_canvas_timestamp_values.sql
- scripts/20161121-col516/update_canvas_course_role_values.sql
- scripts/20161212-col597/add_whiteboards_deleted_at.sql
https://jira.ets.berkeley.edu/jira/browse/COL-580
> COL-580 Add rollback SQL for v1.7 migrations

- config/default.json
- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-core/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-607
> COL-607 Make poller's course deactivation threshold configurable

- node_modules/col-assets/lib/migrate.js
- node_modules/col-assets/lib/rest.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
- public/app/assetlibrary/manageassets/assetLibraryManageAssetsController.js
- public/app/assetlibrary/manageassets/manageassets.html
- scripts/migrate_assets.js
https://jira.ets.berkeley.edu/jira/browse/COL-608
Avoid timeouts while waiting for asset migration to complete.
> COL-608 Allow asset migration to complete in background

- scripts/20161212-col597/add_whiteboards_deleted_at.sql
https://jira.ets.berkeley.edu/jira/browse/COL-580
Master PR is #252
> [QA] COL-580, fix typo in rollback SQL: 'whiteboards' is expected

- scripts/20161212-col597/add_whiteboards_deleted_at.sql
https://jira.ets.berkeley.edu/jira/browse/COL-580
Original PR #248
> COL-580, fix typo in rollback SQL: 'whiteboards' is expected

- node_modules/col-canvas/lib/api.js
- node_modules/col-canvas/tests/util.js
- scripts/20170117-col629/rename_and_hide_suitec_folders.js
https://jira.ets.berkeley.edu/jira/browse/COL-629
https://jira.ets.berkeley.edu/jira/browse/COL-630
We add an explicit _suitec folder check/creation as part of the file upload process, so as to ensure we flag the folder as hidden.
The included script renames and hides existing _collabosphere folders.
> COL-629 COL-630 Rename _collabosphere folder to _suitec; hide folder

- node_modules/col-core/lib/api.js
- node_modules/col-core/tests/test-status.js
- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-631
> COL-631 Add health check for whiteboard thumbnail generation

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-643
`master` will be bumped to 1.9 soonish
> [QA] COL-643, version bump on qa branch

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-643
master branch is v1.9.0
qa PR was #258
> COL-643, version bump on master branch

- .ebextensions/00_ami.config
- .ebextensions/01_create_apache_conf.config
- .ebextensions/02_overwrite_apache_conf.config
- .ebextensions/03_set_node_environment.config
- .ebextensions/04_download_local_configurations.config
- .ebextensions/05_extract_local_configuration.config
- .ebextensions/06_bower_install.config
- .ebextensions/07_build_front_end_assets.config
- .ebextensions/99_delayed_script.config
- .gitignore
https://jira.ets.berkeley.edu/jira/browse/COL-616
> COL-616 Create .ebextensions for Elastic Beanstalk configuration

- .ebextensions/00_ami.config
- .ebextensions/01_create_apache_conf.config
- .ebextensions/02_overwrite_apache_conf.config
- .ebextensions/03_set_node_environment.config
- .ebextensions/04_download_local_configurations.config
- .ebextensions/05_extract_local_configuration.config
- .ebextensions/06_bower_install.config
- .ebextensions/07_build_front_end_assets.config
- .ebextensions/99_delayed_script.config
- .gitignore
https://jira.ets.berkeley.edu/jira/browse/COL-616
eb-master version of #260.
> [eb-master] COL-616 Create .ebextensions for Elastic Beanstalk configuration

- public/app/whiteboards/list/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-569
> COL-569 Voice 'Add Whiteboard' in screenreader

- public/app/whiteboards/board/board.html
https://jira.ets.berkeley.edu/jira/browse/COL-571
> COL-571 Voice whiteboard collaborator online status in screenreader

- public/app/assetlibrary/addlink/addlink.html
- public/app/assetlibrary/edit/edit.html
- public/app/assetlibrary/upload/upload.html
- public/app/engagementindex/points/points.html
- public/app/whiteboards/create/create.html
- public/assets/css/main.css
https://jira.ets.berkeley.edu/jira/browse/COL-566
This pattern is the same as in our bCourses tools (see https://github.com/ets-berkeley-edu/calcentral/pull/3941): put the primary button first in the DOM and order buttons right to left in CSS.
> COL-566 Primary button should precede Cancel button in tabbing sequence

- node_modules/col-whiteboards/lib/api.js
- node_modules/col-whiteboards/tests/test-whiteboards.js
- node_modules/col-whiteboards/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-435
A side effect of this work was to diagnose and fix the mysterious
https://jira.ets.berkeley.edu/jira/browse/COL-583
https://jira.ets.berkeley.edu/jira/browse/COL-628
> COL-435 COL-628 Exclude non-members from online user count; fix whiteboard paging bug

- public/app/whiteboards/edit/whiteboardsEditController.js
https://jira.ets.berkeley.edu/jira/browse/COL-436
> COL-436 Do not show whiteboard removal warning to admins

- node_modules/col-activities/lib/notifications/daily.js
- node_modules/col-activities/lib/notifications/weekly.js
https://jira.ets.berkeley.edu/jira/browse/COL-650
> COL-650 Screen out hidden assets from daily/weekly emails

- node_modules/col-canvas/lib/poller.js
- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-654
These additions will give us noisier logs, but also (one hopes) a better sense of what points in the process are failing.
> COL-654 Additional logging for poller and thumbnail generator

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
The recently cut 'qa' branch is v1.9.0
> NOJIRA, master branch is now v1.10.0

- public/app/assetlibrary/list/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-662
> [QA] COL-662 Remove inequality

- public/app/assetlibrary/list/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-662
> COL-662 Remove inequality

- public/app/whiteboards/board/whiteboardsBoardDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-657
This PR is a matter of rearrangement within the large `whiteboardsBoardDirective.js`. The salient thing is that the `editing:exited` event must be added to the IText prototype _before_ we call `initializeCanvas()`; otherwise, IText objects created within that method won't inherit the event.
> COL-657 Define editing:exited event before initializing whiteboard canvas

- public/app/whiteboards/board/whiteboardsBoardDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-657
QA version of #281.
> [QA] COL-657 Define editing:exited event before initializing whiteboard canvas

- node_modules/col-activities/lib/notifications/daily.js
- node_modules/col-activities/lib/notifications/weekly.js
- node_modules/col-activities/tests/test-daily.js
- node_modules/col-assets/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-650
> COL-650 Screen hidden categories from daily/weekly emails

- node_modules/col-core/lib/logger.js
https://jira.ets.berkeley.edu/jira/browse/COL-422
Ops defeats Rainbow Brite.
> COL-422 Decolorize logs

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
- node_modules/col-whiteboards/lib/api.js
- node_modules/col-whiteboards/tests/util.js
- public/app/whiteboards/exportasassetmodal/exportasasset.html
- public/app/whiteboards/exportasassetmodal/whiteboardsExportAsAssetController.js
https://jira.ets.berkeley.edu/jira/browse/COL-455
and
https://jira.ets.berkeley.edu/jira/browse/COL-668
have occult connections.
> COL-455 COL-668 Generate preview and thumbnail images for exported whiteboards

- node_modules/col-activities/lib/notifications/weekly.js
https://jira.ets.berkeley.edu/jira/browse/COL-535
Regrettably, the weekly email still lacks a test suite.
> COL-535 Omit instructor assets from top asset category in weekly email

- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.css
- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-460
See also https://github.com/ets-berkeley-edu/suitec-preview-service/pull/20
> COL-460 Video preview support in Asset Library

- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-676
> COL-676 Don't show video player for undefined video_url

- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-676
QA version of #293.
> [QA] COL-676 Don't show video player for undefined video_url

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
> NOJIRA, set master branch to version 1.11.0

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/lib/rest.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
- node_modules/col-rest/lib/rest/assets.js
- node_modules/col-whiteboards/lib/api.js
- node_modules/col-whiteboards/lib/rest.js
- public/app/assetlibrary/assetLibraryFactory.js
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.css
- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-419
Say up jump the boogie to the bang bang boogie.
> COL-419 Allow exported whiteboards to be remixed

- node_modules/col-core/lib/db.js
- node_modules/col-course/lib/api.js
- node_modules/col-lti/lib/api.js
- node_modules/col-lti/lib/rest.js
- node_modules/col-lti/tests/util.js
- node_modules/col-rest/lib/rest/lti.js
- public/app/app.states.js
- public/app/dashboard/splash.css
- public/app/dashboard/splash.html
- public/app/dashboard/splashController.js
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-700
https://jira.ets.berkeley.edu/jira/browse/COL-702
https://jira.ets.berkeley.edu/jira/browse/COL-701
Includes:
* wire up pieces associated with `LtiConstants.DASHBOARD` (e.g., cartridge.xml)
* database integration for new tool URL
* v0.01 of splash page has basic user info
> COL-700, new SuiteC tool: /lti/dashboard (Impact Studio)

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/lib/api.js
- node_modules/col-whiteboards/package.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-714
Note that this PR is made against a `1.10.1-patch` branch, as the `qa` branch is already queued up for 1.11.
> COL-714 Avoid crash on errored whiteboard thumbnails

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/lib/rest.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/test-categories.js
- node_modules/col-assets/tests/test-like.js
- node_modules/col-assets/tests/util.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-rest/lib/rest/assets.js
- node_modules/col-whiteboards/tests/util.js
- public/app/app.states.js
- public/app/assetlibrary/assetLibraryFactory.js
- public/app/assetlibrary/assetLibraryService.js
- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/assetlibrary/list/list.html
- public/app/assetlibrary/search/assetLibrarySearchDirective.js
- public/app/assetlibrary/search/search.html
See https://jira.ets.berkeley.edu/jira/browse/COL-674 for screenshot and behavior description.
> COL-674 Sort options for Asset Library

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
> NOJIRA, SuiteC bumps to v1.12

- public/app/assetlibrary/assetLibraryFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-748
The post to `/assets/:id` only requires title, categories and description.
> COL-748, exclude extraneous stuff when submitting asset changes

- bower.json
- public/app/dashboard/dashboardFactory.js
- public/app/dashboard/splash.html
- public/app/dashboard/splashController.js
- public/app/shared/activityTimelineDirective.js
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-736
This PR gets front-end wiring in place, with no pretensions of conforming to any particular design.
> COL-736 Front-end prototype for activity timeline

- public/app/assetlibrary/assetLibraryFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-748
master PR: #312
> [QA] COL-748, exclude extraneous stuff when submitting asset changes

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
Wed Apr 5 [release instructions](https://docs.google.com/document/d/1OOSLmzbro2pg9nsxyIbR5CnOjM7w6tpOiWLxMbtt8gI/edit#) have been updated.
> [QA] NOJIRA, bump version to 1.11.1

- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-746
See https://docs.angularjs.org/api/ng/directive/ngSrc
> COL-746 Fix source tags in asset library detail view

- node_modules/col-core/lib/db.js
- public/app/engagementindex/leaderboard/leaderboardController.js
- public/app/engagementindex/leaderboard/list.html
- public/app/shared/utilService.js
https://jira.ets.berkeley.edu/jira/browse/COL-737
If you hit LTI tool with query args then you risk getting a corrupt URL in the db. We use [Sequelize getters/setters](http://docs.sequelizejs.com/en/latest/docs/models-definition/#getters-setters) to strip query args on create/update.
More "Impact" linking is coming soon.
> COL-737, if Impact LTI tool is installed then link to it from Engagement Index

- public/app/app.states.js
- public/app/assetlibrary/assetLibraryService.js
https://jira.ets.berkeley.edu/jira/browse/COL-764
Deep link to asset without `canvas-customization` dependency. Eg, when linking to asset from user profile (new LTI tool).
> COL-764, link to asset view from tools other than assetLibrary (eg, user profile)

- public/app/app.bootstrap.js
- public/app/assetlibrary/assetLibraryFactory.js
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.html
- public/app/dashboard/myactivity.css
- public/app/dashboard/splash.html
- public/app/dashboard/splashController.js
- public/app/shared/toolHrefDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-755
UX: https://drive.google.com/file/d/0B9vFhXfb6IlZYVc1aENROVdrc3c/view
* For now, 'Most Impactful' = assets sorted by likes.
* If user clicks to view asset from profile then s/he'll get "Return to Dashboard" on asset view.
* Styling on profile page is a work in progress.
> COL-755, profile page gets 'My Assets'; 'Return to Dashboard' from asset view

- public/app/assetlibrary/addlink/addlink.html
- public/app/assetlibrary/upload/upload.html
- public/app/dashboard/myactivity.css
- public/app/dashboard/splash.html
https://jira.ets.berkeley.edu/jira/browse/COL-725
The only change in `dashboard/splash.html` is a wrapper div, with copyright notice at bottom.  Put `?w=1` for simpler diff.
> COL-725, copyright notice to add/edit asset, add whiteboard

- public/app/dashboard/splash.html
- public/app/dashboard/splashController.js
https://jira.ets.berkeley.edu/jira/browse/COL-756
UX: https://drive.google.com/file/d/0B9vFhXfb6IlZYVc1aENROVdrc3c/view
Filters will change per requirements.
> COL-756, swimlane with community assets; for now, filter by recent, comments and likes

- .ebextensions/01_create_apache_conf.config
https://jira.ets.berkeley.edu/jira/browse/COL-708
Follow-up to #301.
> COL-708 Add dashboard RewriteRule to ebextensions

- public/app/dashboard/profileController.js
Such are the hazards of testing locally, with a single user id. Bug fixed.
> COL-756, get assets by user id for My Assets

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-759
UX: https://jira.ets.berkeley.edu/jira/browse/COL-704
I encourage scrutiny on boolean var `showEngagementIndexBox`.
> COL-759, wire up engagement-index box on profile page

- public/app/assetlibrary/assetLibraryFactory.js
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-762
> COL-762 Prototype per-asset activity timeline

- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-759
Null user is a problem.
> COL-759, profile page > sortAssets() after getUser is done

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/shared/utilService.js
https://jira.ets.berkeley.edu/jira/browse/COL-759
The box is wired.
> COL-759 - Engagement Index box gets score, rank and formatting

- public/app/dashboard/profile.html
UX: https://jira.ets.berkeley.edu/jira/browse/COL-704
@paulkerschen Swimlane filter links did not have proper mouseover pointer. What's the right style fix here w.r.t `href`?
> COL-704, updated community asset filters: Trending, Pinned, etc

- node_modules/col-core/lib/logger.js
https://jira.ets.berkeley.edu/jira/browse/COL-782
This PR is a workaround pending a better overall log setup.
> COL-782 Include error details in logger output

- public/app/app.bootstrap.js
- public/app/assetlibrary/assetLibraryService.js
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/shared/hashtagsFilter.js
- public/app/shared/toolHrefDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-754
https://jira.ets.berkeley.edu/jira/browse/COL-759
* styling on top portion of profile (user summary, search, EI box)
* click on hashtag and get custom Asset Library search
* `user.hashtags` is dummy data, for now
> COL-759, profile page formatting (user summary, search, EI box)

- node_modules/col-activities/lib/notifications/daily.js
- node_modules/col-activities/lib/notifications/weekly.js
- node_modules/col-canvas/lib/api.js
- node_modules/col-canvas/lib/poller.js
- node_modules/col-course/lib/api.js
- scripts/20170117-col629/rename_and_hide_suitec_folders.js
- scripts/update_lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-752
The master branch would like to get in on the repointing action.
Equivalent to eb-master PRs #320 and #340.
> [master] COL-752 Script to update LTI configurations in Canvas

- node_modules/col-whiteboards/data/whiteboardToPng.js
https://jira.ets.berkeley.edu/jira/browse/COL-780
Tested out on col-qa.
> COL-780 Scale down large whiteboards on export

- node_modules/col-whiteboards/data/whiteboardToPng.js
https://jira.ets.berkeley.edu/jira/browse/COL-780
eb-master version of #342.
> [eb-master] COL-780 Scale down large whiteboards on export

- node_modules/col-activities/tests/test-daily.js
- node_modules/col-core/lib/constants.js
- node_modules/col-core/lib/db.js
- node_modules/col-course/lib/api.js
- node_modules/col-rest/lib/rest/lti.js
- scripts/update_lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-787
Includes database sanitization from eb-master PR #316; additional format validation in the Courses API; additional error reporting in the LTI repointing script.
> COL-787 Validate tool URLs before storing in db

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-775
Possible date formats:
* 'Today'
* 'Yesterday'
* 'dddd' (if in past 7 days)
* 'MMMM D, YYYY'  (e.g., April 12, 2017)
> COL-775, user.last_activity with smart date format

- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-786
As seen on asset library list view, this is `readonly` view of counts.
> COL-786, My and Everyone's assets on profile get view, like, and comment counts

- node_modules/col-lti/lib/constants.js
- node_modules/col-lti/lib/rest.js
- node_modules/col-rest/lib/rest/lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-706
Who dares to merge this name?
> COL-706, the new LTI tool has been named: Impact Studio

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-745
A follow up to #349
> COL-745, buildspec.yml gets eslint

- public/app/app.states.js
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/dashboard/search/aggregatedSearchController.js
- public/app/dashboard/search/aggregatedSearchDirective.js
- public/app/dashboard/search/results.html
- public/app/dashboard/search/searchform.html
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-792
Search for users/assets from profile.
> COL-792, aggregatedSearch directive and template, used by profile page

- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-746
#315 didn't fix the problem. It's always in the last place you look.
> COL-746 Use ng-attr to avert early fetch attempt on video poster image

- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-746
eb-master version of #352.
> [eb-master] COL-746 Use ng-attr to avert early fetch attempt on video poster image

- public/app/assetlibrary/edit/edit.html
https://jira.ets.berkeley.edu/jira/browse/COL-725
Final nail in the coffin, I hope.
> COL-725, copyright notice on edit asset page

- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/dashboard/profileController.js
- public/app/dashboard/search/aggregatedSearchController.js
- public/app/dashboard/search/aggregatedSearchDirective.js
- public/app/dashboard/search/results.html
- public/app/dashboard/search/searchform.html
- public/app/shared/utilService.js
https://jira.ets.berkeley.edu/jira/browse/COL-794
`$scope.search` properties are structured according to the complexity of aggregatedSearch page. You'll notice cautious code-sharing with `assetLibraryListController`.
> COL-794, aggregatedSearch: findAssets added to front-end controller

- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-799
> COL-799 Use 24-hour format in activity timelines

- node_modules/col-assets/tests/util.js
- node_modules/col-core/lib/db.js
- scripts/20170426-col828/add_impact_trending_to_assets.sql
https://jira.ets.berkeley.edu/jira/browse/COL-828
> COL-828 Add 'impact' and 'trending' columns to assets

- public/app/dashboard/profile.css
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-839
Two small adjustments:
* Because we're not using `multiple` in `oi-select` we get an unwanted arrow in input element. This is not the first oi-select customization in our code...
* The previous placement of `$scope.otherUsers` assignment could have been a problem. Let's avoid the risk.
> COL-839, loadOtherUsers() after loadProfile(); hide oi-select arrow

- node_modules/col-whiteboards/lib/api.js
Note that this logic, as with so much having to do with whiteboards, lives behind the barrier of websockets and is inaccessible to our testing framework.
https://jira.ets.berkeley.edu/jira/browse/COL-824
> COL-824 Create get_whiteboard_add_asset activities for asset creators

- node_modules/col-activities/tests/test-points.js
- node_modules/col-activities/tests/util.js
- node_modules/col-assets/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-837
> COL-837 Add remix_whiteboard and get_remix_whiteboard activities

- node_modules/col-activities/lib/default.js
- node_modules/col-activities/tests/test-types.js
- node_modules/col-activities/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-829
Secret-sauce values from the JIRA are multiplied by 2 to keep everything an integer.
Mentions, cites, and pins are not yet implemeted.
> COL-829 Add impact to activity type configuration

- node_modules/col-activities/lib/default.js
https://jira.ets.berkeley.edu/jira/browse/COL-829
Follow-up to #366.
> COL-829 Deimpactify get_asset_comment_reply

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/util.js
- node_modules/col-assets/lib/api.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-830
`?w=1` review is recommended.
> COL-830 Adjust asset impact scores on activity creation and deletion

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/tests/test-assets.js
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-832
> COL-832 Sort impactful assets by impact

- node_modules/col-canvas/lib/poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-846
eb-master version of #371.
> [eb-master] COL-846 Do not pass null email to users API

- scripts/20170502-col850/add_asset_id_indexes.sql
https://jira.ets.berkeley.edu/jira/browse/COL-850
eb-master version of #373.
> [eb-master] COL-850 Index asset joins for performance

- scripts/20170502-col850/add_asset_id_indexes.sql
https://jira.ets.berkeley.edu/jira/browse/COL-850
~20x speedup verified in suitec-dev.
> COL-850 Index asset joins for performance

- package.json
> [QA] NOJIRA Lock terraformer to 1.0.7

- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-804
As a wise man once said, we are not building a view-as feature.
> COL-804, only show 'Everyone's Assets' swimlane when user is on his/her own profile

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-784
Added `isLoading` for user and community swimlanes. Plus, added some structure to scoped vars.
> COL-784, only show profile swimlanes when isLoading=false

- .eslintrc.yml
- apache/apache.js
- public/app/assetlibrary/assetLibraryFactory.js
- public/app/whiteboards/board/whiteboardsBoardDirective.js
- public/assets/js/bookmarklet.js
Code-style rules brought on in baby steps.
> NOJIRA, enable eslint rule 'no-shadow' and fix offenders

- node_modules/col-activities/tests/test-daily.js
- node_modules/col-core/lib/constants.js
- node_modules/col-course/lib/api.js
- node_modules/col-rest/lib/rest/lti.js
- scripts/update_lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-787
Belated eb-master PR for those parts of #345 not included in #316.
> [eb-master] COL-787 Validate tool URLs before storing in db

- node_modules/col-canvas/lib/api.js
- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/model.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-canvas/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-790
> COL-790 Poller check for removed or hidden tools in Canvas

- README.md
https://jira.ets.berkeley.edu/jira/browse/COL-857
Follows PR #383
Example of mocha-grep:
```
$ npm test -- --grep "Users Points"
Users
Points
Update share status
✓ can be updated (282ms)
✓ is validated (129ms)
Leaderboard
✓ can be retrieved (180ms)
✓ can be retrieved as an instructor (209ms)
✓ verifies authorization (176ms)
5 passing (2s)
```
> COL-857, explain mocha grep in README

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-activities.js
- node_modules/col-activities/tests/util.js
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/shared/activityTimelineDirective.js
- public/app/shared/utilService.js
- public/assets/css/main.css
https://jira.ets.berkeley.edu/jira/browse/COL-858
See screenshot, not identical to designs but getting closer:
> COL-858 Collapse profile activity timeline: six lanes, one pool

- public/app/assetlibrary/backtoreferrer.html
- public/app/assetlibrary/item/item.html
https://jira.ets.berkeley.edu/jira/browse/COL-801
> COL-801, Get back to Impact Studio ... Get back Jojo

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-activities.js
- node_modules/col-activities/tests/util.js
- node_modules/col-core/lib/db.js
https://jira.ets.berkeley.edu/jira/browse/COL-735
The front end will be expecting asset, user, and comment data in the activities feed.
> COL-735 Back end for activity details display

- node_modules/col-core/lib/db.js
https://jira.ets.berkeley.edu/jira/browse/COL-868
Frameworks, frameworks.
> COL-868 Fix Sequelize activity-comment association

- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.html
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/shared/activityTimeline.css
- public/app/shared/activityTimeline.html
- public/app/shared/activityTimelineDirective.js
- public/app/shared/activityTimelineEventDetails.html
- public/app/shared/toolHrefDirective.js
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-735
Screenshot:
> COL-735 Front end for activity details display

- public/app/assetlibrary/search/search.html
- public/app/whiteboards/reuse/reuse.html
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-744
Follow up to PR #395 
Supports search by section when 'Use Existing', as below.
> COL-744, whiteboard > add asset > use existing > search by section

- bower.json
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/whiteboards/create/create.html
- public/app/whiteboards/edit/edit.html
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-864
Warning! Arbitrary justification of `max-length`: [UK Government Data Standards Catalogue](http://webarchive.nationalarchives.gov.uk/+/http://www.cabinetoffice.gov.uk/media/254290/GDS%20Catalogue%20Vol%202.pdf) suggests "70 characters for a single field to hold the Full Name".
The `oi.select` upgrade also comes with `cleanMode` thus fewer CSS overrides.
> COL-864, Impact Studio search input limited to 70 chars

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-points.js
- scripts/recalculate_impact.js
https://jira.ets.berkeley.edu/jira/browse/COL-831
> COL-831 Allow impact scores to be recalculated from stored activities

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-activities.js
- node_modules/col-activities/tests/util.js
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/shared/activityTimeline.css
- public/app/shared/activityTimelineEventDetails.html
https://jira.ets.berkeley.edu/jira/browse/COL-875
Screenshot:
> COL-875 Event details popup for asset detail view

- node_modules/col-activities/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-863
> COL-863 Use app timezone for EI CSV export

- public/app/shared/activityTimeline.html
https://jira.ets.berkeley.edu/jira/browse/COL-825
Screenshot:
> COL-825 Align timeline zoom buttons with swimlanes

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/lib/rest.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
- node_modules/col-rest/lib/rest/assets.js
- public/app/assetlibrary/assetLibraryFactory.js
- public/app/shared/utilService.js
https://jira.ets.berkeley.edu/jira/browse/COL-800
For example, when `filters.hasImpact` is:
* `true` then exclude assets with zero impact
* `false` then include only assets with zero impact
* `null` then do nothing
These filters are primarily for asset exclusion in swimlanes but coded for general purpose.
> COL-800, new filters for getAssets (hasImpact, hasLikes, etc.) benefit swimlanes

- public/app/assetlibrary/assetLibraryFactory.js
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-859
When looking at OPP (other people's profile), words matter.
> COL-859, isMyProfile ? this way : that way

- public/app/dashboard/profile.css
- public/app/shared/activityTimeline.css
- public/app/shared/activityTimeline.html
- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-826
> COL-826 View by Week | Month | All zoom options

- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-880
Sample use case:
And then...
Suggestions on improved wording are welcome.
> COL-880, click 'Most Impactful' > if zero results then proper message and retain filters

- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-883
> COL-883, filters on Community Assets > add 'Most Impactful', remove 'Most Liked'

- node_modules/col-activities/lib/api.js
- node_modules/col-core/lib/api.js
- scripts/recalculate_impact.js
https://jira.ets.berkeley.edu/jira/browse/COL-831
This enhancement allows recalculation of impactulation for all courses in one go, for example after a database refresh.
Also remove the longstanding annoyance of Node scripts scheduling email notifications on startup. This now happens only when the actual app is initialized.
> COL-831 Make course argument optional in impact recalculation script

- .eslintignore
- config/test.js
- config/travis.js
- gulpfile.js
- node_modules/col-analytics/lib/api.js
- node_modules/col-config/lib/rest.js
- node_modules/col-config/tests/test-config.js
- node_modules/col-config/tests/util.js
- node_modules/col-tests/lib/beforeTests.js
- node_modules/col-tests/lib/model.js
- node_modules/col-tests/lib/util.js
- scripts/col-repl.js
- scripts/migrate_assets.js
- scripts/recalculate_impact.js
- scripts/reprocess_previews.js
- scripts/update_lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-884
Notes:
* [`.eslintignore` documentation](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories)
* We leverage a double-negative: Ignore default whereby `node_modules` is ignored.
* Too many violations in `col-activities`, etc. to include fixes in this PR.
* Obsolete scripts are ignored
* These are strictly style fixes.
> COL-884, gulp eslint on node_modules/col-* plus fixes

- public/app/assetlibrary/search/search.html
https://jira.ets.berkeley.edu/jira/browse/COL-886
UX might change.  For now:
> COL-886, Asset Library > Adv Search > sort by Most Impactful

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-activities.js
- node_modules/col-activities/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-889
https://jira.ets.berkeley.edu/jira/browse/COL-891
> COL-889 COL-891 Add activity breakdown counts for user and course to user activities feed

- public/app/app.bootstrap.js
- public/app/assetlibrary/assetLibraryService.js
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/shared/toolHrefDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-887
Notes:
* removed mock hashtag links from profile page (and corresponding tool-href logic)
* toolHrefDirective is now sensitive to change in `data-id`
* Design team will guide us to a better UX. For now, we have...
> COL-887, href, sensitive to swimlane filter selection, gives user link to Asset Library adv search and all results

- node_modules/col-activities/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-889
Fixes bug introduced in #410.
> COL-889 Avoid crash on activities with no defined impact category

- node_modules/col-core/lib/db.js
- node_modules/col-tests/lib/util.js
- node_modules/col-users/lib/constants.js
- scripts/20170516-col900/add_users_personal_bio.sql
https://jira.ets.berkeley.edu/jira/browse/COL-900
Test coverage will come with changes to UsersAPI, next PR. Are we happy with this column naming?
> COL-900, Impact Studio > Alter db: add personal_bio column in 'users' table

- node_modules/col-rest/lib/rest/users.js
- node_modules/col-users/lib/api.js
- node_modules/col-users/lib/rest.js
- node_modules/col-users/tests/test-users.js
- node_modules/col-users/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-901
`/users/me/personal_bio` added to UsersAPI and corresponding tests.
> COL-901, read/write personal_bio via UsersAPI

- public/app/dashboard/activityBreakdown.html
- public/app/dashboard/activityBreakdownDirective.js
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/assets/css/main.css
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-892
https://jira.ets.berkeley.edu/jira/browse/COL-893
> COL-892 COL-893 Front end for activities breakdown

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-activities.js
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-905
> COL-905 Let everyone see everyone else's activity timeline

- public/app/app.states.js
- public/app/dashboard/editProfile.html
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileEditController.js
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-903
Form validation will be the final step of this edit 'personal_bio' work.
> COL-903, 'Edit Profile' link to form with one textarea: personal_bio

- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-903
Inadvertent change in PR #417
> COL-903, fix inadvertent change to 'Edit Profile' label

- public/app/assetlibrary/item/item.html
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/shared/activityTimeline.css
- public/app/shared/activityTimeline.html
- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-865
https://jira.ets.berkeley.edu/jira/browse/COL-899
I still haven't figured out how to correctly space those EventDrops ticks, but we're getting closer.
Narrow:
Wide:
> COL-865 COL-899 Profile page: responsive layout, CSS cleanup

- public/app/assetlibrary/search/assetLibrarySearchDirective.js
- public/app/assetlibrary/search/search.html
https://jira.ets.berkeley.edu/jira/browse/COL-886
Silly rabbit, "impact" is for the special people.
> COL-894, there can be no Impact without a Studio

- public/app/dashboard/editProfile.html
- public/app/dashboard/profile.css
- public/app/dashboard/profileEditController.js
https://jira.ets.berkeley.edu/jira/browse/COL-903
* A couple UX tweaks for our design team to review.
* Shortened ng-model name to reduce noise in markup
* review with `?w=1`
> COL-903, form validation on edit profile page, plus cleanup

- public/app/dashboard/editProfile.html
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-920
Fixes errant CSS shuffling from #419, plus more alphabetizing for a complete breakfast.
> COL-920 Fix profile header CSS

- public/app/dashboard/editProfile.html
https://jira.ets.berkeley.edu/jira/browse/COL-922
The only thing better than 140 chars is 255 chars.
> COL-922, char limit on personal_bio gets a bump

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-921
> COL-921, user description gets linky with it. #hashtags, too

- public/app/shared/activityTimeline.css
- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-923
Goes with https://github.com/ets-berkeley-edu/EventDrops/pull/6.
> COL-923 Activity timelines: specify wrapper element w/ cursor

- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-898
> COL-898 Activity timeline: restore mouse zoom events

- public/app/dashboard/activityBreakdown.html
https://jira.ets.berkeley.edu/jira/browse/COL-925
> COL-925 Verbiage is not complete sentence, gets no full stop

- node_modules/col-course/lib/api.js
- node_modules/col-lti/tests/test-lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-927
> COL-927 Distinguish courses with same Canvas id in different instances

- node_modules/col-course/lib/api.js
- node_modules/col-lti/tests/test-lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-927
eb-master version of #430.
> [eb-master] COL-927 Distinguish courses with same Canvas id in different instances

- public/app/dashboard/editProfile.html
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-803
Better living through buttons.
Sample UI:
> COL-803, buttons instead of links on Impact Studio profile page

- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-862
https://jira.ets.berkeley.edu/jira/browse/COL-872
No test coverage because websockets: sad!
> COL-862 COL-872 Add your own asset to a whiteboard, earn no points, score no impact

- scripts/20170523-col913/add_pinning_activities.sql
- scripts/20170523-col913/create_table_pinned_user_assets.sql
https://jira.ets.berkeley.edu/jira/browse/COL-913
Prior to code changes, I want to confirm proper db schema.
> COL-913, db scripts introduce 'pin' activities_type and pinned_user_assets table

- config/default.json
- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-points.js
- node_modules/col-core/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-906
> COL-906 Periodically recalculate asset trending scores from recent activity

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/lib/rest.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
- node_modules/col-rest/lib/rest/assets.js
https://jira.ets.berkeley.edu/jira/browse/COL-907
> COL-907 Add trending score filtering/ordering to assets API

- public/app/dashboard/profile.html
Small regression created during button work.
> NOJIRA, swimlane label gets colon when totalAssets > 0

- public/app/assetlibrary/assetLibraryFactory.js
- public/app/assetlibrary/search/search.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-888
https://jira.ets.berkeley.edu/jira/browse/COL-908
> COL-888 COL-908 Trending front end

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/lib/default.js
- node_modules/col-core/lib/constants.js
- node_modules/col-core/lib/db.js
https://jira.ets.berkeley.edu/jira/browse/COL-913
Tests will come with AssetsAPI work. This PR confirms sane sequelize setup.
> COL-931, sequelize for pinned_user_assets; default scores of pin activities

- .gitignore
- config/schema.sql
https://jira.ets.berkeley.edu/jira/browse/COL-869
Generated by `pg_dump --schema-only` from suitec-qa.
This file should be regenerated after each migration.
> COL-869 Include database schema in source control

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/tests/util.js
- public/app/assetlibrary/assetLibraryFactory.js
- public/app/assetlibrary/iconbar/AssetLibraryIconBarDirective.js
- public/app/assetlibrary/iconbar/assetLibraryIconBarController.js
- public/app/assetlibrary/iconbar/iconbar.css
- public/app/assetlibrary/iconbar/iconbar.html
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.css
- public/app/assetlibrary/item/item.html
- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/assetlibrary/list/list.html
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/dashboard/search/results.html
- public/app/shared/utilService.js
https://jira.ets.berkeley.edu/jira/browse/COL-915
UX: https://jira.ets.berkeley.edu/jira/browse/COL-808
List and detail view in Asset Library get basic pinning function.
> COL-915, UI changes (icons, etc.) in Asset Library per pinning

- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/engagementindex/leaderboard/leaderboardController.js
https://jira.ets.berkeley.edu/jira/browse/COL-947
A few trial balloons to test Mixpanel behavior.
> COL-947 Initial front-end analytics on profile page

- node_modules/col-assets/tests/test-bookmarklet.js
For review, not necessarily for merging.
This is by way of getting my first day's homework checked before I move to the LRS. @johncrossman , @paulkerschen , @pfarestveit , @sandeepmjay , would you mind taking a look? Thanks!
> NOJIRA Sample Mocha approach

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/lib/default.js
The work of https://jira.ets.berkeley.edu/jira/browse/COL-914 ("points per pinning activities") will get done for Fall 2017. For the Jun 15 deploy, we will prioritize in-progress features and bug fixing.
> NOJIRA, hide pin activity types from Engagement index > points configuration

- public/app/assetlibrary/list/list.css
- public/app/assetlibrary/list/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-950
The blue is matched to Canvas navigation tabs. See screenshot:
> COL-950 Badges: front end

- public/app/assetlibrary/iconbar/assetLibraryIconBarController.js
- public/app/assetlibrary/iconbar/iconbar.html
- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/assetlibrary/list/list.html
- public/app/assetlibrary/search/search.html
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/dashboard/search/searchform.html
https://jira.ets.berkeley.edu/jira/browse/COL-957
Click pin icon below asset preview to toggle status of myPin. Doing so fires `assetPinEventByMe` events which, in some cases, cause search results (or profile page swimlane) to reload appropriately.
**Bonus:** "Uploader" is now "User" per https://jira.ets.berkeley.edu/jira/browse/COL-953
> COL-957, pin/unpin from asset-icon-bar; listen for assetPinEventByMe events

- public/app/assetlibrary/list/list.html
- public/app/dashboard/profile.html
- public/app/shared/assetThumbnail.html
https://jira.ets.berkeley.edu/jira/browse/COL-950
> COL-950 Badges in the Impact Studio; extract shared thumbnail template

- public/app/assetlibrary/iconbar/iconbar.css
https://jira.ets.berkeley.edu/jira/browse/COL-968
https://jira.ets.berkeley.edu/jira/browse/COL-966
Feeling blue?
> COL-968, update pin-icon colors: inactive, hover, active

- public/app/assetlibrary/iconbar/iconbar.html
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-969
A chicken in every pot and an `id` on every button.
> COL-969, profile page and asset-iconbar get ids on buttons and hrefs

- public/app/assetlibrary/item/item.html
- public/app/whiteboards/reuse/reuse.css
- public/app/whiteboards/reuse/reuse.html
https://jira.ets.berkeley.edu/jira/browse/COL-919
John approves of this PR. But will Paul?
> COL-919, my pinned first in listing of Whiteboards > Add asset

- public/app/shared/activityTimeline.css
- public/app/shared/activityTimeline.html
- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-933
A bit of compensation for changes in https://github.com/ets-berkeley-edu/EventDrops/pull/8, which should be merged first.
> COL-933 Adjust to saner EventDrops dimensions

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-970
> COL-970, Impact Studio > filter > move count next to action label

- bower.json
- public/app/assetlibrary/iconbar/assetLibraryIconBarController.js
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/whiteboards/board/whiteboardsBoardDirective.js
- public/assets/js/bookmarklet.js
https://jira.ets.berkeley.edu/jira/browse/COL-978
Lodash changelog: https://github.com/lodash/lodash/wiki/Changelog
As first done in PR #186
> COL-978, front-end Lodash upgraded to 4.17.4

- public/app/dashboard/activityBreakdown.html
- public/app/dashboard/activityBreakdownDirective.js
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-975
(Holding off for the moment on the red-for-impacts color change, until we've sorted out how it will play with any modifications to EventDrops.)
> COL-975 Rework contributions bar chart based on user tests

- node_modules/col-assets/lib/rest.js
- public/app/assetlibrary/assetLibraryFactory.js
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-947
What is an Asset Library search? Chocolate.
What is an Impact Studio profile? Peanut butter.
You know what to do.
> COL-947 Do not record asset library searches in analytics when loading Impact Studio

- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-947
> COL-947 More Impact Studio activity tracking

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-910
Expected UI:
> COL-976, browse other users alphabetically with previous|next nav

- node_modules/col-users/lib/rest.js
- public/app/dashboard/profileController.js
- public/app/shared/activityTimelineDirective.js
- public/app/shared/userFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-947
Retrieving users for the Impact Studio should not be tracked as an Engagement Index request.
> COL-947 Impact studio analytics: add timeline zoom, remove EI listing

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/tests/test-search.js
- node_modules/col-assets/tests/util.js
- public/app/whiteboards/reuse/reuse.html
- public/app/whiteboards/reuse/whiteboardsReuseController.js
https://jira.ets.berkeley.edu/jira/browse/COL-988
Because it just makes sense.
> COL-988, getAssets: 'order by pins' is, to be more specific, ordered by pin.created_at desc

- public/app/whiteboards/reuse/whiteboardsReuseController.js
https://jira.ets.berkeley.edu/jira/browse/COL-967
A butterfly flaps its wings in `whiteboardsReuseController` and all hell breaks loose.
> COL-967, whiteboard search-for-existing-assets > sort-by > now it worky

- public/app/dashboard/activityBreakdown.html
https://jira.ets.berkeley.edu/jira/browse/COL-985
Even those who don't contribute deserve nice formatting.
> COL-985 Spacing fix for 'Currently no contributions/impacts'

- public/app/dashboard/profile.css
https://jira.ets.berkeley.edu/jira/browse/COL-986
Cascade, sweet stylesheets, till I end my song.
> COL-986 Wrap, don't truncate, activity breakdown labels

- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-989
Refresh directive when `data-activity-timeline` is modified.
I recommend `w=1`.
> COL-989, activityTimelineDirective will refresh when model object is updated

- public/app/shared/activityTimeline.css
- public/app/shared/activityTimelineEventDetails.html
https://jira.ets.berkeley.edu/jira/browse/COL-942
> COL-942 Fallback icon for missing asset thumbnails in timeline

- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-940
"The staff was friendly but the rendering was soggy... would not go back"
> COL-940 Disable metaballs on Safari

- public/app/shared/activityTimeline.css
https://jira.ets.berkeley.edu/jira/browse/COL-895
> COL-895 Align timeline zoom buttons

- node_modules/col-assets/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-988
Pin sort by user when user is not me gives pins sorted as if you were me. Oh, never mind.
> COL-988, sort order :user_id must match SELECT clause :user_id

- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-992
> COL-992 Update timeline start/end on activity refresh

- node_modules/col-activities/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-992
Sequelize must be asked extra nice when ordering on associations.
> COL-992 Fix ordering in activity feeds

- public/app/dashboard/activityBreakdownDirective.js
- public/app/dashboard/profile.css
https://jira.ets.berkeley.edu/jira/browse/COL-998
It matches the eventdrops, don't you know.
> COL-998 Impacts bar chart should be colored Impact Rouge

- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-990
Course with...
* less than 2 users gets no search browse
* two users gets UX below
* three or more users gets standard experience
I recommend `?w=1`
---
> COL-990, search-for-people if you're an admin who is not part of the roster, etc.

- buildspec.yml
- scripts/generate-buildspec-report.sh
https://jira.ets.berkeley.edu/jira/browse/COL-1004
This is step one. Let's make sure the YAML makes it to suitec-dev before I code `col-core/lib/api.js getVersion` to read the file.
> COL-1004, SuiteC /api/version gets git.branch and git.commit

- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-972
Expected UI of 'My Assets':
----
Expected UI of 'Assets' (some other user):
----
> COL-972, User with 1+ pins and zero uploaded assets needs filters in 'Assets' swimlane

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/model.js
- node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1001
> COL-1001 Ignore Canvas submissions in unsubmitted state

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/model.js
- node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1001
QA version of #497.
> [QA] COL-1001 Ignore Canvas submissions in unsubmitted state

- public/app/whiteboards/edit/whiteboardsEditController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1006
`master` PR to follow
Lodash upgrade was PR #465
> [QA] COL-1006, Lodash 4 did away with deprecated _.include

- public/app/whiteboards/edit/whiteboardsEditController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1006
`qa` PR is #499
> COL-1006, Lodash 4 did away with deprecated _.include

- public/app/app.bootstrap.js
- public/app/assetlibrary/assetLibraryService.js
- public/app/assetlibrary/backToReferrerController.js
- public/app/assetlibrary/backtoreferrer.html
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.html
- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/assetlibrary/list/list.html
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/engagementindex/leaderboard/leaderboardController.js
- public/app/shared/toolHrefDirective.js
- public/app/shared/toolHrefHashtagFilter.js
- public/app/shared/utilService.js
https://jira.ets.berkeley.edu/jira/browse/COL-802
Worth noting:
*  profileController must scroll-to-position _after_ all assets loaded, thus the callbacks
* `crossToolRequest` instead `referringTool` allows us to ditch prefix 'requested' on id and scroll
* use `?w=1`
> COL-802, new tool-href args (scroll, referringScroll) for proper focus when Return to Dashboard

- .ebextensions/00_ami.config
- .ebextensions/01_create_apache_conf.config
https://jira.ets.berkeley.edu/jira/browse/COL-1012
QA version of #503.
> [QA] COL-1012 Switch load balancer listener settings to elbv2

- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-802
`scroll` is one property we want to forget when browsing other users.
> COL-802, ignore scroll when search/browse other users

- node_modules/col-core/lib/email.js
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1015
Per examples at https://github.com/sendgrid/sendgrid-nodejs, code needed to interact with Sendgrid looks rather different these days.
> COL-1015 Update Sendgrid version and API

- node_modules/col-core/lib/email.js
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1015
QA version of #508.
> [QA] COL-1015 Update Sendgrid version and API

- gulpfile.js
https://jira.ets.berkeley.edu/jira/browse/COL-1027
> [QA] COL-1027 Include unversioned images for email templates in gulpfile

- bower.json
- package.json
- public/app/app.bootstrap.js
- public/app/app.states.js
- public/app/assetlibrary/item/item.html
- public/app/assetlibrary/list/list.html
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/shared/toolHrefDirective.js
- public/app/shared/utilService.js
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-802
If we return user to previous scroll position then we must also restore previous filters. This PR repurposes `referringScroll`.  We use `referringState` to serialize page state.
> COL-802, 'Return to Dashboard' restores selected filters and previous scroll position

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-991
No wrap. No outline.
> COL-991, more responsive user pagination in profile view

- public/app/assetlibrary/backtoreferrer.html
https://jira.ets.berkeley.edu/jira/browse/COL-802
...and pass back `referringState`, too.
> COL-802, fix lazy mistake in backtoreferrer.html

- public/app/assetlibrary/addbookmarklet/addbookmarklet.css
- public/app/assetlibrary/item/item.css
- public/app/assetlibrary/manageassets/manageassets.css
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/shared/activityTimeline.css
- public/app/shared/apiError.css
- public/app/whiteboards/board/board.css
- public/assets/css/bookmarklet.css
- public/assets/css/main.css
https://jira.ets.berkeley.edu/jira/browse/COL-991
* Simplified markup/CSS for w.r.t filters
* Addressed some `csslint` complaints
> COL-991, responsive UI for asset filters on profile page

- node_modules/col-canvas/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1035
> COL-1035 Add conversation posting to Canvas API client

- public/app/assetlibrary/search/search.html
https://jira.ets.berkeley.edu/jira/browse/COL-878
Code is also used by 'Whiteboards > Add asset'
> COL-878, a bit more width for category and uploader filters (Asset Library)

- node_modules/col-rest/lib/rest/users.js
- node_modules/col-users/lib/api.js
- node_modules/col-users/lib/rest.js
- node_modules/col-users/tests/test-users.js
- node_modules/col-users/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1036
There's not really a good place for this API in our current structure, but the users module is perhaps the least bad.
> COL-1036 API endpoint and tests for Canvas conversation messaging

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/lib/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-914
`col-assets/lib/api.js` was nearing critical mass.
> COL-914, col-assets/lib/api.js: helper functions moved to util.js

- gulpfile.js
Use MOCHA_GREP or
```
gulp mocha --grep "A subset of all tests"
```
> NOJIRA, gulp mocha > use MOCHA_GREP or '--grep' arg

- node_modules/col-rest/lib/rest/users.js
- node_modules/col-users/lib/api.js
- node_modules/col-users/lib/rest.js
- node_modules/col-users/tests/test-users.js
- node_modules/col-users/tests/util.js
- public/app/shared/userFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-1029
> COL-1029 API and front-end factory to toggle User.looking_for_collaborators

- public/app/dashboard/editProfile.html
- public/app/dashboard/lookingForCollaborators.html
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1030
Display on other people's profiles comes next.
> COL-1030 Looking for collaborators: front-end toggle

- public/app/dashboard/lookingForCollaborators.html
- public/assets/css/main.css
https://jira.ets.berkeley.edu/jira/browse/COL-1031
> COL-1031 Collaboration indicator button on other peeps' profiles

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/lib/default.js
- node_modules/col-activities/lib/util.js
- node_modules/col-activities/tests/test-points.js
- node_modules/col-assets/lib/api.js
- node_modules/col-assets/tests/test-search.js
- node_modules/col-assets/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-914
* pinning, under the hood, is identified as first-time or a repeat (re-pin)
* actor_id is needed in get_pin / get_repin logic
* helper functions moved to  `col-activities/lib/util.js`
> COL-914, record activities pin, repin, get_pin, get_repin

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-991
Design for mobile first: https://www.w3schools.com/css/css_rwd_mediaqueries.asp
> COL-991, other-users-container and profile-filters: @media screen rule (mobile is default) 

- node_modules/col-analytics/lib/api.js
- public/app/assetlibrary/iconbar/assetLibraryIconBarController.js
- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-934
Our customer (ie, John Scott) requested tracking of 'pin' events; 'unpin' events are ignored.
`asset_pin_count` added to _col-analytics/lib/api.js_.
> COL-934, track pinning of assets (analytics)

- public/app/assetlibrary/item/assetLibraryItemController.js
- public/app/assetlibrary/item/item.css
- public/app/assetlibrary/item/item.html
- public/app/shared/collaborationMessageModal.html
- public/app/shared/collaborationMessageService.js
https://jira.ets.berkeley.edu/jira/browse/COL-1033
The green buttons expand their reach.
> COL-1033 Looking for Collaborators in asset detail view

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/lib/default.js
- node_modules/col-assets/tests/test-search.js
- public/app/dashboard/activityBreakdown.html
- public/app/dashboard/activityBreakdownDirective.js
- public/app/dashboard/profile.css
- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1049
UX: https://jira.ets.berkeley.edu/jira/browse/COL-948
* pin_asset > impact score = 5
* all pin-related are "interactions" per reqts
* 'remixes' to end of the line
* pin / get_pin added to visualizations
> COL-1049, visualizations and Impact Score for pinning

- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-991
* 768px as used in assetlibrary/item.css and whiteboards/reuse.css 
* do not hide delimiter of browse-user
> COL-991, @media rule min-width: 768px per SuiteC standard

- public/app/dashboard/profileSearchAutosuggestFilter.js
https://jira.ets.berkeley.edu/jira/browse/COL-1034
Looking to collaborate? Show it to the world... in the Impact Studio user profile search dropdown!
> COL-1034 Add collaboration icon to user search dropdown

- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-999
> COL-999, analytics > record browse-other-user event

- node_modules/col-activities/lib/notifications/daily.js
- node_modules/col-activities/lib/rest.js
- node_modules/col-activities/tests/test-daily.js
- node_modules/col-activities/tests/util.js
- node_modules/col-rest/lib/rest/activities.js
https://jira.ets.berkeley.edu/jira/browse/COL-1013
For example: `/1452646/activities/notifications/send_daily` (admin only)
> COL-1013, new email-related endpoint: send-daily-email

- public/app/dashboard/activityBreakdown.html
- public/app/dashboard/activityBreakdownDirective.js
- public/app/dashboard/activityTimelineLabelDetails.html
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/shared/activityTimeline.css
- public/app/shared/activityTimelineDirective.js
- public/app/shared/activityTimelineEventDetails.html
https://jira.ets.berkeley.edu/jira/browse/COL-1042
Front-end code to make your eyes cross!
> COL-1042 Revised explanatory text for activity visualizations

- public/app/whiteboards/reuse/reuse.html
https://jira.ets.berkeley.edu/jira/browse/COL-1048
The QA Dept will be your best friend if you merge this PR.
> COL-1048, asset ID per checkbox in markup of whiteboards > use-existing-asset

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-activities.js
https://jira.ets.berkeley.edu/jira/browse/COL-1052
> COL-1052 Exclude deleted assets from coursewide activity counts

- public/app/dashboard/editProfile.html
https://jira.ets.berkeley.edu/jira/browse/COL-1054
What type of collaboration do you like?
> COL-1054, editProfile to include 'Collaboration Interests'

- public/app/dashboard/editProfile.html
https://jira.ets.berkeley.edu/jira/browse/COL-1054
master PR #545
> [QA] COL-1054, editProfile to include 'Collaboration Interests'

- public/app/dashboard/activityBreakdown.html
- public/app/dashboard/activityBreakdownDirective.js
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1058
Some changes to mollify the stern eye of QA.
- "Compared to Others" is reverted to the more strictly correct "Compared to Everyone";
- Counts for "Everyone" are converted to averages showing a single decimal place (the rationale being that this makes weird zeroes less likely);
- People other than you are not called "you".
> COL-1058 Contributions breakdown: textual revisions

- public/app/dashboard/activityBreakdown.html
- public/app/dashboard/activityBreakdownDirective.js
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1058
QA version of #548.
> [QA] COL-1058 Contributions breakdown: textual revisions

- public/app/shared/activityTimelineDirective.js
- public/app/shared/activityTimelineEventDetails.html
https://jira.ets.berkeley.edu/jira/browse/COL-1056
Also clear out some controller code not used in the new UX.
> COL-1056 Add missing activity descriptions to timeline

- public/app/shared/activityTimelineDirective.js
- public/app/shared/activityTimelineEventDetails.html
https://jira.ets.berkeley.edu/jira/browse/COL-1056
QA version of #551.
> [QA] COL-1056 Add missing activity descriptions to timeline

- public/app/dashboard/activityBreakdownDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1058
Follow-up to #548.
> COL-1058 Round coursewide average activity counts

- public/app/dashboard/activityBreakdownDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1058
Follow-up to #550, QA version of #554.
> [QA] COL-1058 Round coursewide average activity counts

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-points.js
https://jira.ets.berkeley.edu/jira/browse/COL-1059
master PR: #553
> [QA] COL-1059, if pinner is co-owner of the asset then his collaborators get neither "pin" nor "get_pin" credit

- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1061
master PR: #557
> [QA] COL-1061, reset user preferences when loading new user profile

- public/app/shared/activityTimeline.html
- public/app/shared/activityTimelineDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-937
https://jira.ets.berkeley.edu/jira/browse/COL-995
- Fix inconsistent zoom behavior for timelines less than a month long;
- Disable zoom-out button when at maximum zoom;
- Skip transition animations on initial page load.
> COL-937 COL-995 Timeline zoom enhancements

- public/app/dashboard/activityBreakdown.html
- public/app/dashboard/activityBreakdownDirective.js
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-1063
https://jira.ets.berkeley.edu/jira/browse/COL-1064
> COL-1063 COL-1064 Grammar time

- public/app/dashboard/activityBreakdown.html
- public/app/dashboard/activityBreakdownDirective.js
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-1063
https://jira.ets.berkeley.edu/jira/browse/COL-1064
QA version of #560
> [QA] COL-1063 COL-1064 Grammar time

- public/app/whiteboards/reuse/reuse.html
- public/app/whiteboards/reuse/whiteboardsReuseController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1065
The need for QA PR is TBD.
> COL-1065, no apology for zero results until !isLoading

- public/app/whiteboards/reuse/reuse.html
- public/app/whiteboards/reuse/whiteboardsReuseController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1065
master PR: #562
> [QA] COL-1065, no apology for zero results until !isLoading

- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/assetlibrary/list/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-1069
We only need this check on initial page load.
> COL-1069, no 'No assets' msg until NOT isLoading

- public/app/assetlibrary/list/assetLibraryListController.js
- public/app/assetlibrary/list/list.html
https://jira.ets.berkeley.edu/jira/browse/COL-1069
master PR: #565 
Merge if fix is wanted in v2.1 release.
> [QA] COL-1069, no 'No assets' msg until NOT isLoading

- public/app/assetlibrary/list/assetLibraryListController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1069
QA PR is #567
> COL-1069, isLoading=true during subsequent searches in Asset Library

- docs/deployment.md
https://jira.ets.berkeley.edu/jira/browse/COL-1072
Preview of what users will see:
https://github.com/johncrossman/suitec/blob/COL-1072_no-more-suitec-ops/docs/deployment.md
> COL-1072, remove suitec-ops related info in docs/deployment.md

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-1073
The true test will be CodePipeline.
> COL-1073, remove 'npm install' and 'gulp eslint' from buildspec (CodePipeline)

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
> NOJIRA, bump version to 2.2

- public/app/assetlibrary/item/assetLibraryItemController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1076
More powder blue dots for asset detail.
> COL-1076, asset detail gets a new lane: Pinned

- public/app/assetlibrary/assetLibraryService.js
https://jira.ets.berkeley.edu/jira/browse/COL-1082
> COL-1082 Type check in assetViewRedirect

- public/app/assetlibrary/assetLibraryService.js
https://jira.ets.berkeley.edu/jira/browse/COL-1082
QA version of #575.
> [QA] COL-1082 Type check in assetViewRedirect

- app.js
- node_modules/col-assets/lib/migrate.js
- node_modules/col-canvas/lib/poller.js
- node_modules/col-core/lib/api.js
- node_modules/col-core/lib/db.js
- node_modules/col-core/lib/modules.js
- node_modules/col-core/lib/rest.js
- node_modules/col-core/lib/server.js
- node_modules/col-core/tests/test-status.js
- node_modules/col-lti/lib/api.js
- node_modules/col-lti/tests/test-lti.js
- node_modules/col-rest/lib/rest/core.js
- node_modules/col-tests/lib/beforeTests.js
- public/app/app.bootstrap.js
- public/app/app.states.js
- public/app/shared/infiniteScrollDirective.js
- public/app/shared/utilService.js
- public/assets/js/bookmarklet.js
- scripts/20160525-col378/populate_element_asset_id.js
- scripts/col-repl.js
- scripts/migrate_assets.js
- scripts/reprocess_previews.js
Far fewer syllables in the codebase.
> NOJIRA, in comments and logging: Collabosphere is now SuiteC

- config/default.json
- node_modules/col-core/lib/storage.js
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1084
S3 bucket and key naming convention as proposed in
* http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html
* My design doc (draft): https://goo.gl/sypx2c
Next step will be fileDelete, tests and the swapping out of Canvas Files API.
> COL-1084, AWS S3 to storeAsset (replace CanvasAPI.uploadFileToCanvas)

- config/schema.sql
- node_modules/col-core/lib/db.js
- scripts/20170711-col1104/add_whiteboards_aws_s3_object_key.sql
https://jira.ets.berkeley.edu/jira/browse/COL-1109
See description of PR #585
> COL-1109, db modification: add_whiteboards_aws_s3_object_key

- node_modules/col-core/lib/storage.js
https://jira.ets.berkeley.edu/jira/browse/COL-1110
Naming convention w.r.t storing whiteboard images in Amazon S3 (formerly image_url)
> COL-1110, add support to storeWhiteboardImage in S3

- scripts/refresh-data.sh
https://jira.ets.berkeley.edu/jira/browse/COL-1111
The script can be run on any environment, including dev machines, as long as source and destination configs are present.
> COL-1111 Update source environment for data refresh script to suitec-prod

- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1113
This facepalm of a bug is another no-test-coverage special.
> COL-1113 Fix asset ownership check when adding to whiteboard

- scripts/pull-data.sh
https://jira.ets.berkeley.edu/jira/browse/COL-1116
> COL-1116 Include impact_score and trending_score in db refresh script

- node_modules/col-canvas/lib/poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1117
> COL-1117 Include reciprocal_id in get_discussion_entry_reply activities

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
> NOJIRA, bump version on master to 2.3.0

- config/default.json
- config/test.js
- node_modules/col-analytics/lib/api.js
- node_modules/col-analytics/lib/mixpanel.js
- node_modules/col-config/lib/api.js
- node_modules/col-config/tests/util.js
- node_modules/col-lti/lib/api.js
- public/app/app.config.js
https://jira.ets.berkeley.edu/jira/browse/COL-1121
Move over, Mixpanel, and make room for IMS Caliper, the standard of the future!
I've documented in release instructions a required change to local configs on suitec-qa and suitec-prod (but not on suitec-dev or developer machines, which are not hooked up to Mixpanel).
> COL-1121 Separate Mixpanel code and configs from overall analytics

- node_modules/col-analytics/lib/caliper.js
https://jira.ets.berkeley.edu/jira/browse/COL-1123
See below for a sample event as shown in logs. This code bundles into Caliper format the user and course data that we have on hand. Richer information such as referrer and session ID will require better integration with the Node HTTP stack.
```
{
"@context": "http://purl.imsglobal.org/ctx/caliper/v1p1",
"id": "urn:uuid:512b05b5-868e-42dd-b78e-e6fb1b8eb645",
"type": "NavigationEvent",
"actor": {
"id": "https://ucberkeley.beta.instructure.com/users/5144274",
"type": "Person",
"name": "Paul Kerschen"
},
"action": "NavigatedTo",
"object": {
"id": "https://app-dev.ets-berkeley-suitec.net/lti/dashboard.xml",
"type": "SoftwareApplication",
"name": "Impact Studio",
"version": "2.3.0"
},
"eventTime": "2017-07-25T18:57:38.045Z",
"group": {
"id": …
```
> COL-1123 Caliper instrumentation for LTI launch events

- node_modules/col-analytics/lib/api.js
- node_modules/col-analytics/lib/caliper.js
- node_modules/col-analytics/tests/test-caliper.js
- node_modules/col-analytics/tests/util.js
- node_modules/col-assets/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-1125
> COL-1125 Caliper instrumentation: asset view, list, search

- node_modules/col-assets/lib/rest.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/util.js
- node_modules/col-rest/lib/rest/assets.js
https://jira.ets.berkeley.edu/jira/browse/COL-573
You are not allowed to download asset if:
* not 'active'
* AND not admin user
> COL-573, perform auth check prior to asset download

- node_modules/col-analytics/lib/api.js
- node_modules/col-analytics/lib/caliper.js
- node_modules/col-analytics/tests/test-caliper.js
- node_modules/col-analytics/tests/util.js
- node_modules/col-assets/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-1127
> COL-1127 Caliper instrumentation: commenting

- node_modules/col-analytics/lib/caliper.js
- node_modules/col-analytics/tests/test-caliper.js
https://jira.ets.berkeley.edu/jira/browse/COL-1129
The hits keep coming!
> COL-1129 Caliper instrumentation: Engagement Index

- node_modules/col-analytics/lib/caliper.js
- node_modules/col-analytics/tests/test-caliper.js
- node_modules/col-whiteboards/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-1130
> COL-1130 Caliper instrumentation: whiteboard view events

- node_modules/col-analytics/lib/caliper.js
- node_modules/col-analytics/tests/test-caliper.js
- node_modules/col-rest/lib/rest/whiteboards.js
- node_modules/col-whiteboards/lib/api.js
- node_modules/col-whiteboards/lib/rest.js
- node_modules/col-whiteboards/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1132
Instrumentation on chat message creation has been tested locally, but has no automated coverage because of those old websockets.
> COL-1132 Caliper instrumentation: whiteboard chat messages

- node_modules/col-analytics/lib/caliper.js
- node_modules/col-analytics/tests/test-caliper.js
- node_modules/col-whiteboards/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-1133
> COL-1133 Caliper instrumentation: whiteboard export

- node_modules/col-assets/tests/test-assets.js
- node_modules/col-assets/tests/test-migrate.js
- node_modules/col-assets/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1085
More test coverage...
> COL-1085, test coverage for S3 to S3 asset file migration

- node_modules/col-analytics/lib/caliper.js
- node_modules/col-analytics/tests/test-caliper.js
- node_modules/col-whiteboards/lib/api.js
- node_modules/col-whiteboards/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-1131
> COL-1131 Caliper instrumentation: whiteboard creation and editing

- node_modules/col-canvas/lib/poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1139
> COL-1139 Avoid misleading dead-poller alert when no courses are active

- node_modules/col-activities/lib/notifications/daily.js
- node_modules/col-activities/lib/notifications/weekly.js
- node_modules/col-canvas/lib/poller.js
- node_modules/col-course/lib/api.js
- package.json
- scripts/20170117-col629/rename_and_hide_suitec_folders.js
- scripts/move_canvas_files_to_amazon_s3.js
- scripts/update_lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-1106
Usage: `$0  --after [YYYY-MM-DD] --before [YYYY-MM-DD]` 
Canvas files are not removed after move is done – we don't want a bug in the script to cause a catastrophic loss of content. This script generates a CSV file which lists all "obsolete" files in Canvas. Once the move to Amazon S3 has been verified we can delete files in Canvas using these CSV(s).
> COL-1106, script to move Canvas files to Amazon S3

- public/app/shared/analyticsService.js
https://jira.ets.berkeley.edu/jira/browse/COL-1163
Do not seek after a Mixpanel that is not there. Fly on your own wings.
> COL-1163 Do not attempt front-end setup of disabled Mixpanel

- public/app/shared/analyticsService.js
Zap that JS console error: https://jira.ets.berkeley.edu/jira/browse/COL-1167
> COL-1167 Add noop track function when front-end analytics disabled

- scripts/move_canvas_files_to_amazon_s3.js
It's well-nigh impossible to reason through exactly what's going wrong with the async flow in https://jira.ets.berkeley.edu/jira/browse/COL-1165, but here's a shot at clearing it up.
> COL-1165 S3 migration script: attempt to guard against duplicate callbacks

- node_modules/col-core/lib/storage.js
https://jira.ets.berkeley.edu/jira/browse/COL-1160
> COL-1160 Truncate filenames to prevent overlong S3 URIs

- gulpfile.js
https://jira.ets.berkeley.edu/jira/browse/COL-1166
> COL-1166 Suppress favicon.ico 404 errors

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-categories/lib/api.js
- node_modules/col-categories/lib/rest.js
- public/app/assetlibrary/manageassets/manageassets.html
https://jira.ets.berkeley.edu/jira/browse/COL-1178
> COL-1178 Do not display sync option for assigments without syncable submission types

- scripts/move_canvas_files_to_amazon_s3.js
https://jira.ets.berkeley.edu/jira/browse/COL-1171
* Error handling/prevention improvements
* More informative output
* No empty CSVs
> COL-1171, move_canvas_files_to_amazon_s3 script: more validation, catch uncaught errors and improve output/CSVs

- node_modules/col-canvas/lib/poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1178
More async control flow (sigh) as a follow up to #634, which broke suitec-dev.
> COL-1178 Short-circuit submission processing for non-syncable assignments

- scripts/move_canvas_files_to_amazon_s3.js
https://jira.ets.berkeley.edu/jira/browse/COL-1170
* fix logic of date range
* s3 filename uniqueness
* async.eachOfSeries for clearer code
* improved summary
> COL-1170, async.eachOfSeries, for courses and assets, to simplify callback; s3 filename uniqueness

- scripts/move_canvas_files_to_amazon_s3.js
https://jira.ets.berkeley.edu/jira/browse/COL-1155
* two SQL queries with narrow result-sets
* generic `moveFileToAmazonS3` function
* asset and whiteboard files listed in same CSV
> COL-1155, script move_canvas_files_to_amazon_s3 will migrate whiteboard image_url files

- scripts/move_canvas_files_to_amazon_s3.js
https://jira.ets.berkeley.edu/jira/browse/COL-1179
Review with `?w=1`
QA PR coming soon.
> COL-1179, S3 migration script (1) tolerates failures per file and (2) includes assets of type 'whiteboard'

- scripts/move_canvas_files_to_amazon_s3.js
https://jira.ets.berkeley.edu/jira/browse/COL-1179
master PR: #639
> [QA] COL-1179, S3 migration script (1) tolerates failures per file and (2) includes assets of type 'whiteboard'

- node_modules/col-canvas/lib/api.js
- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-canvas/tests/util.js
- node_modules/col-core/lib/storage.js
https://jira.ets.berkeley.edu/jira/browse/COL-1181
https://jira.ets.berkeley.edu/jira/browse/COL-1162
Ideally, we can limit the app's S3 permissions to create and read. The app must not overwrite or delete files.
> COL-1181, never literally delete files in Amazon S3 or Canvas filesystem

- node_modules/col-canvas/lib/api.js
- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-canvas/tests/util.js
- node_modules/col-core/lib/storage.js
https://jira.ets.berkeley.edu/jira/browse/COL-1181
https://jira.ets.berkeley.edu/jira/browse/COL-1162
master PR #643
> [QA] COL-1181, never literally delete files in Amazon S3 or Canvas filesystem

- node_modules/col-activities/tests/test-activities.js
- node_modules/col-activities/tests/test-daily.js
- node_modules/col-activities/tests/test-points.js
- node_modules/col-activities/tests/util.js
- node_modules/col-assets/tests/test-bookmarklet.js
- node_modules/col-assets/tests/test-search.js
- node_modules/col-assets/tests/util.js
- node_modules/col-canvas/tests/test-poller.js
- node_modules/col-categories/tests/util.js
- node_modules/col-config/tests/util.js
- node_modules/col-core/tests/test-status.js
- node_modules/col-course/tests/test-course.js
- node_modules/col-course/tests/util.js
- node_modules/col-lti/tests/util.js
- node_modules/col-tests/lib/beforeTests.js
- node_modules/col-users/tests/util.js
- node_modules/col-whiteboards/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1182
For example, in a `recalculateImpactScores` test I added:
```
assert.ifError(new Error('something bad happened'));
```
The error message surfaced after Mocha had run _all_ tests.
> COL-1182, assert.ifError(err) will give error details if err

- scripts/move_canvas_files_to_amazon_s3.js
https://jira.ets.berkeley.edu/jira/browse/COL-1179
Two fixes:
* delete temp file after it has been pushed to S3
* no err to callback in context of `async.eachOfSeries`
> COL-1179, if request to Canvas fails then recordFailure() but do not bail

- scripts/move_canvas_files_to_amazon_s3.js
https://jira.ets.berkeley.edu/jira/browse/COL-1179
master PR is #648
> [QA] COL-1179, if request to Canvas fails then recordFailure() but do not bail

- README.md
- node_modules/col-assets/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-1194
* SuiteC dev is lifelong learning
* update README with link to proper Canvas LMS install instructions
> COL-1194, view and download of hidden assets is allowed

- node_modules/col-assets/lib/api.js
- node_modules/col-assets/lib/rest.js
https://jira.ets.berkeley.edu/jira/browse/COL-1194
I've been bitten by idiosyncratic async.  I recommend `?w=1`
> COL-1194, collaborator can see whiteboard assets put by other collaborator

- scripts/20170928-col1108/clean_up_canvas_after_s3_migration.js
https://jira.ets.berkeley.edu/jira/browse/COL-1107
Many bits stolen from our `move_to_s3` script. Ops will recognize the usage info.
> COL-1107, now that S3-migration is done, clean up Canvas filesystem

- node_modules/col-analytics/tests/util.js
This one has plagued Travis more often of late.
> NOJIRA Fix intermittent test failure on Caliper events

- node_modules/col-assets/lib/rest.js
- node_modules/col-core/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1203
Just another day on the ranch.
> COL-1203 URI-encode filename header when downloading assets

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/COL-1212
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-applicationloadbalancer.html
> COL-1212 Enable session stickiness in .ebextensions

- scripts/20170928-col1108/clean_up_canvas_after_s3_migration.js
https://jira.ets.berkeley.edu/jira/browse/COL-1217
Usage info says it all.
> COL-1217, Canvas clean up script now accepts canvas_course_id arg

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
Under this version number the Activity Network is expected to meet the world.
> NOJIRA Version bump 2.5

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/lib/rest.js
- node_modules/col-activities/tests/test-activities.js
- node_modules/col-activities/tests/util.js
- node_modules/col-rest/lib/rest/activities.js
https://jira.ets.berkeley.edu/jira/browse/COL-1223
> COL-1223 Student-to-student activities API feed

- scripts/20170928-col1108/clean_up_canvas_after_s3_migration.js
https://jira.ets.berkeley.edu/jira/browse/COL-1233
If neither folder is found then report the 404 to 'notFound' file.
> COL-1233, clean_up_canvas script looks for '_collabosphere' folder if '_suitec' was not found

- scripts/20170928-col1108/clean_up_canvas_after_s3_migration.js
https://jira.ets.berkeley.edu/jira/browse/COL-1236
Read about `timeout` option and read timeouts at https://github.com/request/request 
We leverage `canvasPoller.timeout` config
> COL-1236, clean_up_canvas script > increase timeout for delete requests

- node_modules/col-activities/lib/api.js
- node_modules/col-activities/tests/test-activities.js
https://jira.ets.berkeley.edu/jira/browse/COL-1224
> COL-1224 Add whiteboard co-creations to activities feed

- scripts/20170928-col1108/clean_up_canvas_after_s3_migration.js
https://jira.ets.berkeley.edu/jira/browse/COL-1237
> COL-1237, clean-up script checks for both _collabosphere and _suitec

- .eslintrc.yml
- node_modules/col-activities/lib/api.js
- node_modules/col-activities/lib/rest.js
- node_modules/col-activities/tests/test-activities.js
- node_modules/col-activities/tests/util.js
- node_modules/col-core/lib/constants.js
- node_modules/col-rest/lib/rest/activities.js
- public/app/dashboard/activityNetwork.html
- public/app/dashboard/activityNetworkDirective.js
- public/app/dashboard/activityNetworkTooltip.html
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
- public/app/dashboard/profileController.js
- public/app/dashboard/profileFactory.js
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-1222
Refinements to come.
> COL-1222 First-round Activity Network implementation

- public/app/dashboard/activityNetworkDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1229
> COL-1229 Adjust Activity Network size and charge depending on course size

- node_modules/col-users/lib/api.js
- node_modules/col-users/lib/rest.js
- public/app/dashboard/activityNetworkDirective.js
- public/app/dashboard/activityNetworkTooltip.html
- public/app/dashboard/profile.css
- public/app/dashboard/profileController.js
- public/app/shared/userFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-1226
Note the expanded canvas_full_name for the selected user (useful in a course site with two Pauls, for example).
> COL-1226 Activity network interaction details tooltip

- public/app/dashboard/activityNetworkDirective.js
- public/app/dashboard/activityNetworkTooltip.html
- public/app/dashboard/profile.css
https://jira.ets.berkeley.edu/jira/browse/COL-1228
> COL-1228 Special handling for 'me'

- public/app/dashboard/activityNetworkTooltip.html
- public/app/dashboard/profile.css
https://jira.ets.berkeley.edu/jira/browse/COL-1226
Follow-up tweak to #675.
> COL-1226 Adjust arrow spacing in tooltip

- public/app/dashboard/activityNetwork.html
- public/app/dashboard/activityNetworkDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1229
An approach in progress to deal with the size of the W4C network. Adding pan behavior entails losing the (fun but useless) drag behavior where you could grab and bounce individual people's heads at will.
> COL-1229 Cropping and panning for activity network

- public/app/dashboard/activityNetworkDirective.js
- public/app/dashboard/activityNetworkTooltip.html
- public/app/dashboard/profile.css
- public/app/dashboard/profile.html
https://jira.ets.berkeley.edu/jira/browse/COL-1227
> COL-1227 Add 'Looking for Collaborators' to Activity Network

- public/app/dashboard/activityNetwork.html
- public/app/dashboard/activityNetworkDirective.js
- public/app/dashboard/profile.css
https://jira.ets.berkeley.edu/jira/browse/COL-1229
Do these make the tool more usable, or less? The viewers will decide!
> COL-1229 Zoom controls for Activity Network

- public/app/dashboard/activityNetworkDirective.js
- public/app/dashboard/activityNetworkTooltip.html
https://jira.ets.berkeley.edu/jira/browse/COL-1229
Also HTML ids on user node elements for QA dept.
> COL-1229 Activity Network: text changes

- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1245
> COL-1245 Pop non-student activity bubbles

- public/app/dashboard/activityNetworkDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1249
Includes a tapering function for line thickness, now that we have properly large numbers.
> COL-1249 One is the loneliest number

- public/app/dashboard/activityNetworkDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1250
> COL-1250 Special handling for whiteboard co-creation

- public/app/dashboard/activityNetworkDirective.js
- public/app/dashboard/activityNetworkTooltip.html
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1247
> COL-1247 Activity Network: refocusable user nodes

- public/app/dashboard/activityNetworkDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1248
> COL-1248 Activity network: further fade unconnected nodes on mouseover

- public/app/dashboard/activityNetworkDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1244
> COL-1244 Activity network: handle node deselection on touch devices

- node_modules/col-lti/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1246
> COL-1246 Preserve LTI-provided enrollment state on user launch

- public/app/dashboard/activityNetworkDirective.js
See https://jira.ets.berkeley.edu/jira/browse/COL-1251 for a full description of the bugs.
> COL-1251 Fix errant link displays

- public/app/shared/copyright.html
https://jira.ets.berkeley.edu/jira/browse/COL-1252
QA PR coming soon.
> COL-1252, copyright 2018

- public/app/shared/copyright.html
https://jira.ets.berkeley.edu/jira/browse/COL-1252
master PR #691
> [QA] COL-1252, copyright 2018

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1215
> COL-1215 Remove empty assignment categories if assignment goes away

- .ebextensions/04_download_local_configuration.config
https://jira.ets.berkeley.edu/jira/browse/COL-1281
> COL-1281 Apply stricter permissions to config/local-production.json

- scripts/20180208-col1283/create_events_table.sql
https://jira.ets.berkeley.edu/jira/browse/COL-1283
* I chose not to include foreign key constraints. This is an audit log and should not 'cascade on delete' or similar.
* The not-null columns: event_name, event_metadata, canvas_domain
> COL-1283, create db table to track 'events' a la MixPanel

- config/schema.sql
- node_modules/col-analytics/lib/api.js
- node_modules/col-analytics/lib/caliper.js
- node_modules/col-analytics/lib/event.js
- node_modules/col-analytics/lib/util.js
- node_modules/col-core/lib/db.js
- node_modules/col-lti/lib/rest.js
- package.json
- scripts/20180208-col1283/create_events_table.sql
https://jira.ets.berkeley.edu/jira/browse/COL-1285
* `created_at/updated_at` in events table
* `async.parallel` to speed up event transaction, hopefully
*  coming soon: share the CaliperAPI utils which inspect `object` and `contextObject`
> COL-1285, events def in schema.sql; AnalyticsAPI writes events to db

- node_modules/col-analytics/lib/caliper.js
- node_modules/col-analytics/lib/constants.js
- node_modules/col-analytics/lib/event.js
- node_modules/col-analytics/lib/util.js
- node_modules/col-core/lib/db.js
https://jira.ets.berkeley.edu/jira/browse/COL-1286
The `events` table gets object ids, when available. Event types are categorized with hope of a sensible switch statement. Tests are in next PR.
> COL-1286, event-types are categorized based on primary object association (eg, asset)

- README.md
- config/schema.sql
- node_modules/col-analytics/lib/event.js
- node_modules/col-analytics/lib/util.js
- node_modules/col-analytics/tests/test-caliper.js
- node_modules/col-analytics/tests/test-event.js
- node_modules/col-analytics/tests/util.js
- node_modules/col-assets/tests/test-assets.js
- node_modules/col-lti/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1285
A couple tests and a couple fixes.
> COL-1285, AnalyticsAPI > Event test coverage; small fixes

- node_modules/col-analytics/tests/test-event.js
- node_modules/col-analytics/tests/util.js
- node_modules/col-whiteboards/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1285
Last `event` tracking test, for now.
> COL-1285, verify event when create whiteboard and create element

- node_modules/col-core/lib/db.js
- node_modules/col-rest/lib/rest/users.js
- node_modules/col-users/lib/rest.js
- node_modules/col-users/lib/util.js
- node_modules/col-users/tests/test-users.js
- node_modules/col-users/tests/util.js
- package.json
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1292
The crucial bit of server-side logic:
```
if (!me.is_admin && me.id !== user.id && (!me.share_points || !user.share_points)) {
// exclude points from JSON
...
}
```
Includes fix in profile view: `$scope.userRank` not properly null'ed in user pagination.
> COL-1292, do not serve data in JSON feed to unauthorized users

- node_modules/col-core/lib/db.js
- node_modules/col-rest/lib/rest/users.js
- node_modules/col-users/lib/rest.js
- node_modules/col-users/lib/util.js
- node_modules/col-users/tests/test-users.js
- node_modules/col-users/tests/util.js
- package.json
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1292
master PR is #710
> [QA] COL-1292, do not serve data in JSON feed to unauthorized users

- scripts/reprocess_previews.js
https://jira.ets.berkeley.edu/jira/browse/COL-1277
> COL-1277 Provide optional asset id to preview reprocessing script

- bower.json
- node_modules/col-analytics/lib/event.js
- node_modules/col-analytics/lib/rest.js
- node_modules/col-analytics/lib/util.js
- node_modules/col-analytics/tests/test-event.js
- public/app/app.bootstrap.js
- public/app/app.config.js
- public/app/shared/analyticsService.js
- public/app/shared/utilService.js
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-1297
https://jira.ets.berkeley.edu/jira/browse/COL-1299
We do our best to extract object ids. And, remove extraneous and duplicative info from event_metadata object.
> COL-1297, remove client-side mixpanel.track(); scrub metadata

- bower.json
- node_modules/col-analytics/lib/event.js
- node_modules/col-analytics/lib/rest.js
- node_modules/col-analytics/lib/util.js
- node_modules/col-analytics/tests/test-event.js
- node_modules/col-analytics/tests/util.js
- node_modules/col-rest/lib/api.js
- node_modules/col-rest/lib/rest/events.js
- public/app/app.bootstrap.js
- public/app/app.config.js
- public/app/shared/analyticsService.js
- public/app/shared/utilService.js
- public/index.html
https://jira.ets.berkeley.edu/jira/browse/COL-1297
https://jira.ets.berkeley.edu/jira/browse/COL-1299
https://jira.ets.berkeley.edu/jira/browse/COL-1301
master PRs: #715 #714
> [QA] COL-1297, remove client-side mixpanel.track(); COL-1301, rest endpoint to track

- node_modules/col-assets/lib/rest.js
- node_modules/col-core/lib/util.js
- node_modules/col-core/tests/test-util.js
- node_modules/col-whiteboards/lib/rest.js
- public/app/whiteboards/board/whiteboardsBoardDirective.js
- public/app/whiteboards/exportasassetmodal/whiteboardsExportAsAssetController.js
- public/app/whiteboards/whiteboardsFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-1294
https://jira.ets.berkeley.edu/jira/browse/COL-1293
* Not all `getWhiteboard()` calls are equal.
* 'Upload asset' is not 'download asset'
> COL-1294, track=false if getWhiteboard invoked from export-as-asset modal

- node_modules/col-assets/lib/rest.js
- node_modules/col-core/lib/util.js
- node_modules/col-core/tests/test-util.js
- node_modules/col-whiteboards/lib/rest.js
- public/app/whiteboards/board/whiteboardsBoardDirective.js
- public/app/whiteboards/exportasassetmodal/whiteboardsExportAsAssetController.js
- public/app/whiteboards/whiteboardsFactory.js
https://jira.ets.berkeley.edu/jira/browse/COL-1294
https://jira.ets.berkeley.edu/jira/browse/COL-1293
master PR is #717
> [QA] COL-1294, track=false if getWhiteboard invoked from export-as-asset modal

- public/app/whiteboards/board/whiteboardsBoardDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1317
master PR is #719
> [QA] COL-1317, append 'track' to URL with proper query arg connector

- README.md
- node_modules/col-core/lib/db.js
- node_modules/col-users/lib/util.js
- node_modules/col-users/tests/test-users.js
https://jira.ets.berkeley.edu/jira/browse/COL-1313
A local `npm test` reports 16 errors. But the same 16 errors are reported on the master branch, so I'm curious about what Travis will think...
> COL-1313 Suppress user email address in feed

- public/app/dashboard/profile.css
https://jira.ets.berkeley.edu/jira/browse/COL-1324
> COL-1324 Give that Activity Network a border

- public/app/dashboard/activityNetworkDirective.js
- public/app/dashboard/activityNetworkTooltip.html
https://jira.ets.berkeley.edu/jira/browse/COL-1328
`?w=1` will reveal there's less here than meets the eye.
> COL-1328 Activity Network: Enable user details popup on big center node

- config/default.json
- node_modules/col-config/lib/api.js
- node_modules/col-config/tests/util.js
- public/app/dashboard/activityNetwork.html
- public/app/dashboard/activityNetworkDirective.js
- public/app/dashboard/profile.css
- public/app/dashboard/profileController.js
https://jira.ets.berkeley.edu/jira/browse/COL-1325
> COL-1325 Activity network: recent/all toggle

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
> NOJIRA, master branch of SuiteC > version bumped to 2.9.0

- public/app/dashboard/activityNetwork.html
- public/app/dashboard/activityNetworkDirective.js
https://jira.ets.berkeley.edu/jira/browse/COL-1329
> [QA] COL-1329, call the filter "Last 90 Days" instead of "Recent"

- node_modules/col-users/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1333
> COL-1333 Please don't destructively modify the UserConstants

- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1343
> COL-1343, replace paulkerschen/caliper-js with ets-berkeley-edu/caliper-js

- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1343
Master PR: https://github.com/ets-berkeley-edu/suitec/pull/739
> [QA] COL-1343, replace paulkerschen/caliper-js with ets-berkeley-edu/caliper-js

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
Prod is currently running 2.8.1
> [QA] NOJIRA, bump SuiteC release candidate to v2.8.2

- .ebextensions/01_create_apache_conf.config
- .ebextensions/99_delayed_script.config
https://jira.ets.berkeley.edu/jira/browse/COL-1342
Tested manually on suitec-dev and seems to work.
> COL-1342 Modify CloudWatch config to pick up Apache logs under correct names

- node_modules/col-activities/lib/notifications/weekly.js
https://jira.ets.berkeley.edu/jira/browse/COL-1356
> COL-1356 Handle inactive users in weekly email

- node_modules/col-activities/lib/notifications/weekly.js
https://jira.ets.berkeley.edu/jira/browse/COL-1356
QA version of #751.
> [QA] COL-1356 Handle inactive users in weekly email

- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1357
https://jira.ets.berkeley.edu/jira/browse/COL-1358
> [QA] COL-1358, COL-1357, Security vulnerabilities patched: mime=1.6.0 and pg=6.1.6

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
> [QA] NOJIRA, bump version on suitec/qa to 2.8.6

- bower.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1379
> COL-1379, lodash upgrade in bower.json and package.json

- node_modules/col-assets/lib/api.js
- node_modules/col-core/lib/db.js
- node_modules/col-core/lib/storage.js
- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1380
> COL-1380 Re-sign image preview URLs as needed

- bower.json
- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1379
master PR is #759
> [QA] COL-1379, lodash upgrade in bower.json and package.json

- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1380
QA-first follow-up to #761.
> [QA] COL-1380 One more signed-URL fix for whiteboards

- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1380
Master-branch version of #763.
> COL-1380 One more signed-URL fix for whiteboards

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1391
master PR coming soon
> [QA] COL-1391, ignore assignment submissions where workflow_state=pending_upload

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/model.js
- node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1391
> [QA] COL-1391, ignores active submission if attachment is in pending_upload state

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/model.js
- node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1391
This PR has commits from QA PRs #765 and #767
DO NOT MERGE until COL-1391 has been closed/verified on suitec-qa
> COL-1391, ignore assignment submissions where workflow_state=pending_upload

- node_modules/col-canvas/lib/poller.js
- node_modules/col-canvas/tests/model.js
- node_modules/col-canvas/tests/test-poller.js
https://jira.ets.berkeley.edu/jira/browse/COL-1391
Reverts PRs #765, #767.
> COL-1391 Revert earlier attachment submission code changes

- node_modules/col-activities/lib/notifications/daily.js
- node_modules/col-activities/lib/notifications/weekly.js
- node_modules/col-activities/lib/util.js
- node_modules/col-activities/tests/util.js
- node_modules/col-core/lib/db.js
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1389
I'll create a less urgent follow up Jira to do away with 'operatorsAliases'.  See http://docs.sequelizejs.com/manual/querying.html#operators-security
> COL-1389, upgrade Sequelize to v5.8.7

- .ebextensions/10_bower_install.config
https://jira.ets.berkeley.edu/jira/browse/COL-1395
See log file attached to Jira.  This is a hasty experiment to see if the bower command needs all the extra dressing.
> COL-1395, simplify commands in .ebextensions/10_bower_install.config

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
The only thing better than a `package.json`  is 14 of them.
> NOJIRA, SuiteC master branch bumped to v2.10.0

- node_modules/col-lti/lib/api.js
- node_modules/col-lti/tests/util.js
- node_modules/col-rest/lib/rest/lti.js
https://jira.ets.berkeley.edu/jira/browse/COL-1401
> COL-1401 Use custom LTI param rather than HTTP referer for tool URL

- node_modules/col-lti/lib/api.js
- node_modules/col-lti/tests/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1402
> COL-1402 Adjust Canvas-provided LTI param for external tool URLs

- node_modules/col-course/lib/api.js
- node_modules/col-lti/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1401 and https://jira.ets.berkeley.edu/jira/browse/COL-1402 end with a whimper.
> COL-1402 Attempt fallback to LTI-provided tool URL only if referer is unhelpful

- node_modules/col-assets/lib/api.js
- node_modules/col-whiteboards/lib/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1404
> COL-1404 Sequelize eager loading for exported whiteboards is too blessed eager

- node_modules/col-lti/lib/rest.js
- node_modules/col-whiteboards/lib/rest.js
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1410
https://jira.ets.berkeley.edu/jira/browse/CLC-7207
> COL-1410 Update cookie properties for Chrome 80

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
> [QA] NOJIRA, qa branch version bumped from 2.10 to 2.11

- node_modules/col-activities/package.json
- node_modules/col-analytics/package.json
- node_modules/col-assets/package.json
- node_modules/col-canvas/package.json
- node_modules/col-categories/package.json
- node_modules/col-config/package.json
- node_modules/col-core/package.json
- node_modules/col-course/package.json
- node_modules/col-lti/package.json
- node_modules/col-rest/package.json
- node_modules/col-tests/package.json
- node_modules/col-users/package.json
- node_modules/col-whiteboards/package.json
- package.json
SuiteC v2.10.0 is already in prod (https://app-prod.ets-berkeley-suitec.net/api/version)
> NOJIRA, master branch version: 2.10 to 2.12

- buildspec.yml
> NOJIRA, buildspec: 'nvm use' prior to npm install

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-1411
Informed by https://github.com/lodash/lodash/issues/4358
> [QA] COL-1411, CodeBuild fails on npm 3.10.3; force npm 3.10.10 to fix

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-1411
QA PR is #791 
`suitec-qa` pipeline liked this change.
> COL-1411, CodeBuild fails on npm 3.10.3; force npm 3.10.10 to fix (master)

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-1416
> COL-1416 CodeBuild version 2 upgrade

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-1436
> COL-1436 Buildspec Node 10 updates

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-1436
> COL-1436 CodeBuild doesn't want to be micromanaged

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-1436
> COL-1436 Yum is not yummy without -y

- .ebextensions/00_ami.config
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1436
> COL-1436 Config changes for Amazon Linux 2 environment
